module.exports.exercisesDirectory = {
  exercises: [
    {
      mph: '4',
      met: '7',
      name: 'Jogging (13 -18 min/mile)',
      rpm: 0,
      type: 'Cardio',
      id: '0UQkgtO7hl4HwLBKJJhU',
    },
    {
      met: '14.6',
      type: 'Cardio',
      rpm: 0,
      name: 'Running (Sub 8 min/mile)',
      mph: '7.5',
      id: '0nWqXkBMT3ZvPl43rAtR',
    },
    {
      met: '5',
      type: 'Sport',
      mph: 0,
      rpm: 0,
      name: 'Tennis Volley (Non-Game)',
      id: '1UtjJD6UAk31naaUROul',
    },
    {
      rpm: 0,
      type: 'Cardio',
      mph: '10',
      met: '5.9',
      name: 'Stationary Bike',
      id: '1pZCycD0Zw9imPw9EALl',
    },
    {
      met: '7',
      rpm: 0,
      name: 'Swimming - Sidestroke (Competition)',
      type: 'Cardio',
      mph: '4',
      id: '2x5Kj24hN5c8xYirHQlO',
    },
    {
      mph: 0,
      name: 'Full Cobra',
      met: '3.5',
      rpm: '27.2',
      type: 'Brunch Body',
      id: '3VEW9tp1IdmgBrSgfDvb',
    },
    {
      mph: 0,
      rpm: 0,
      met: '3.8',
      name: 'Gymnastics',
      type: 'Exercise',
      id: '3gAHj2ecm62Xpzc0kV5y',
    },
    {
      name: 'Elliptical',
      rpm: 0,
      met: '5.06',
      type: 'Cardio',
      mph: 0,
      id: '40xULi0HxAVj7sGhoCfk',
    },
    {
      rpm: '27.2',
      mph: 0,
      met: '3.5',
      type: 'Exercise',
      name: 'Calisthenics',
      id: '56MpmjxLNupet8ZhJAl6',
    },
    {
      met: '2.5',
      mph: 0,
      rpm: 0,
      type: 'Sport',
      name: 'Catch (Baseball/Football)',
      id: '5oWFqo7tjQHxBOpkXTrd',
    },
    {
      met: '3.5',
      name: 'Band Lateral Raise',
      rpm: '27.2',
      mph: 0,
      type: 'Brunch Body',
      id: '641WwdYWD9xKoyGBmWJr',
    },
    {
      rpm: 0,
      type: 'Sport',
      mph: 0,
      met: '6.5',
      name: 'Basketball, Outdoor',
      id: '6LU8exqEqs14Q2xV2Xu7',
    },
    {
      met: '3',
      name: 'Standing Crunches',
      mph: 0,
      rpm: '30',
      type: 'Brunch Body',
      id: '76Qg7Iz4fFSeAucMw5Of',
    },
    {
      met: '3.5',
      type: 'Brunch Body',
      rpm: '27.2',
      mph: 0,
      name: 'Band Side Bends',
      id: '7AlVGSuSG38ro8UN5zoO',
    },
    {
      met: '2.65',
      type: 'Exercise',
      mph: 0,
      name: 'Abdominal Exercise',
      rpm: '40',
      id: '7MIGoWNxjfL1LqIgnMsC',
    },
    {
      met: '8',
      rpm: 0,
      type: 'Sport',
      mph: 0,
      name: 'Football (American)',
      id: '88grnynyM3Ty1fkfpZyj',
    },
    {
      rpm: 0,
      mph: '10',
      met: '10.6',
      type: 'Cardio',
      name: 'Mountain Biking',
      id: '8KxJnOpsa1BECIKgYOzM',
    },
    {
      mph: 0,
      met: '4.5',
      type: 'Sport',
      rpm: 0,
      name: 'Volleyball',
      id: '8anq04EHbrKLjSWphJpi',
    },
    {
      rpm: 0,
      type: 'Sport',
      name: 'Golf (W/ Cart)',
      mph: 0,
      met: '2.5',
      id: 'B5QV4fRwErtImjSnybwG',
    },
    {
      name: 'Squats',
      rpm: '40',
      type: 'Exercise',
      mph: 0,
      met: '3.5',
      id: 'CyRjFPNi86D4GgivZswR',
    },
    {
      mph: 0,
      met: '3.5',
      rpm: '27.2',
      type: 'Brunch Body',
      name: 'Hip Bridge',
      id: 'DHTGg7BmoIX6NHy7HUt8',
    },
    {
      type: 'Brunch Body',
      met: '3.5',
      mph: 0,
      rpm: '27.2',
      name: 'Walking Burpee',
      id: 'DksC2iS21AJSzzGNOycl',
    },
    {
      met: '11.3',
      type: 'Cardio',
      name: 'Jump Rope',
      rpm: 0,
      mph: 0,
      id: 'EnBdGVrTV4ojjnqoeHzt',
    },
    {
      rpm: 0,
      met: '7.1',
      mph: '3',
      name: 'Hiking (20 min/mile)',
      type: 'Cardio',
      id: 'F8kSwNROeorcVIezPdbb',
    },
    {
      rpm: 0,
      type: 'Sport',
      met: '6',
      mph: 0,
      name: 'Softball, Pitching',
      id: 'FRLqsUu3RiTIrqF48tIs',
    },
    {
      met: '3.5',
      mph: 0,
      name: 'Swimming - Treading water',
      type: 'Cardio',
      rpm: 0,
      id: 'G2oG5c2QhgmE8Lj2zHzP',
    },
    {
      name: 'Downhill Skiing (racing)',
      rpm: 0,
      type: 'Cardio',
      mph: 0,
      met: '8',
      id: 'GIiEpelEofJtNpT0Kmku',
    },
    {
      rpm: 0,
      name: 'Skiing',
      type: 'Cardio',
      mph: 0,
      met: '7',
      id: 'HG4PE8vLiMkLN79ZmCDl',
    },
    {
      rpm: 0,
      name: 'Squash',
      mph: 0,
      met: '12',
      type: 'Sport',
      id: 'HNhaOv2xIr1Le8GnC325',
    },
    {
      rpm: 0,
      type: 'Cardio',
      name: 'Snowboarding',
      met: '5.3',
      mph: 0,
      id: 'HTOVQBiAKW7oOhmf02vF',
    },
    {
      name: 'Weight Lifting',
      met: '4.8',
      rpm: '9.75',
      type: 'Exercise',
      mph: 0,
      id: 'Hre9w4kWbOqabpdB0HXo',
    },
    {
      type: 'Exercise',
      name: 'Aerobics',
      mph: 0,
      met: '6.5',
      rpm: 0,
      id: 'I3p4nTdDj8KZtSQ4O4ov',
    },
    {
      met: '4',
      mph: 0,
      rpm: '30',
      type: 'Brunch Body',
      name: 'Mountain Climber',
      id: 'IBHIdxmCzjlfVWc6oEBG',
    },
    {
      mph: '8',
      met: '12',
      type: 'Cardio',
      rpm: 0,
      name: 'Sculling',
      id: 'IStr3353C5QF6dB6uPJN',
    },
    {
      rpm: '30',
      met: '4',
      type: 'Brunch Body',
      name: 'Reverse Lunge W/ Twist',
      mph: 0,
      id: 'JUbt5TaO4bIBQnjGOsdH',
    },
    {
      met: '8',
      mph: 0,
      name: 'Flag Football',
      rpm: 0,
      type: 'Sport',
      id: 'JxPTom5ELAh6zZwirseF',
    },
    {
      rpm: 0,
      mph: '3',
      met: '5',
      type: 'Cardio',
      name: 'Kayaking',
      id: 'K6VHgHV9n1DSfMD7h1hd',
    },
    {
      met: '9',
      rpm: 0,
      mph: 0,
      name: 'Ice Hockey',
      type: 'Sport',
      id: 'KOtBUSf462V0DpeH2Bgg',
    },
    {
      met: '3',
      name: 'Golf (Driving Range)',
      mph: 0,
      rpm: 0,
      type: 'Sport',
      id: 'Kdp3ka2vCLOchC4gfE83',
    },
    {
      met: '6',
      rpm: 0,
      name: 'Wrestling Sparing',
      mph: 0,
      type: 'Sport',
      id: 'NbJd5IuVIBoqTJAsgojh',
    },
    {
      type: 'Sport',
      met: '8',
      rpm: 0,
      name: 'Tennis (Singles)',
      mph: 0,
      id: 'O0x6v0GoFZi8g49xVECQ',
    },
    {
      met: '4',
      rpm: '30',
      type: 'Exercise',
      mph: 0,
      name: 'Burpee',
      id: 'OvHPxoOwomqv03jn8dAF',
    },
    {
      met: '13.8',
      name: 'Swimming - Butterfly (Competition)',
      rpm: 0,
      mph: '4',
      type: 'Cardio',
      id: 'PgMJwIenMSWuovTmBtzP',
    },
    {
      met: '6.35',
      type: 'Cardio',
      name: 'Bicycling (commuting)',
      rpm: 0,
      mph: '10',
      id: 'QTohuzvmZHCPbU2doVdi',
    },
    {
      met: '10.3',
      mph: '4',
      name: 'Swimming - Breaststroke (Competition)',
      rpm: 0,
      type: 'Cardio',
      id: 'RJcvckX2mMgiBc3Halo2',
    },
    {
      rpm: '22',
      name: 'Kettlebells',
      met: '9.8',
      type: 'Exercise',
      mph: 0,
      id: 'RKZZRQLzsxuuBUanaMrE',
    },
    {
      type: 'Sport',
      met: '7.8',
      mph: 0,
      name: 'Martial Arts',
      rpm: 0,
      id: 'RY2WGw3ZACiG3tlSvZPU',
    },
    {
      met: '3.5',
      rpm: '27.2',
      name: 'Box Pushup',
      type: 'Brunch Body',
      mph: 0,
      id: 'RjYuurdeCjh38M9JJcye',
    },
    {
      name: 'Plank',
      rpm: 0,
      mph: 0,
      met: '3.5',
      type: 'Exercise',
      id: 'S03AW3rb2rcTg30xjDLu',
    },
    {
      met: '2.95',
      rpm: 0,
      name: 'Yoga',
      type: 'Exercise',
      mph: 0,
      id: 'SmG7OAxU3qGJXf8nfvc9',
    },
    {
      met: '4.8',
      type: 'Cardio',
      rpm: 0,
      name: 'Swimming - Backstroke',
      mph: '2',
      id: 'Su7ZxYsmjCkXquaI9GmR',
    },
    {
      met: '5.5',
      rpm: 0,
      type: 'Cardio',
      name: 'Water Aerobics',
      mph: 0,
      id: 'T4DhZ4VRS4i27yfdFPPT',
    },
    {
      rpm: '30',
      type: 'Exercise',
      name: 'Push ups',
      met: '3.3',
      mph: 0,
      id: 'TWSlWw8yhPL5MsJuJ7ii',
    },
    {
      mph: '4',
      met: '10',
      rpm: 0,
      name: 'Swimming - Crawl (Competition)',
      type: 'Cardio',
      id: 'TekgeUpIEKWAdY9a6ybd',
    },
    {
      met: '3.5',
      name: 'Walking (20 min/mile)',
      type: 'Cardio',
      mph: '3',
      rpm: 0,
      id: 'U1BwyaN3wC208sCBTKWJ',
    },
    {
      rpm: 0,
      type: 'Cardio',
      mph: 0,
      name: 'Cone Drills',
      met: '8',
      id: 'UEmjpnBqBFNGTaQwqjLw',
    },
    {
      met: '3.1',
      name: 'Pull ups',
      rpm: '6',
      mph: 0,
      type: 'Exercise',
      id: 'UcyPPuyMphT96YTMinRj',
    },
    {
      met: '5',
      mph: 0,
      name: 'Golf (Walking)',
      rpm: 0,
      type: 'Sport',
      id: 'VeRnKgQMHgll2Pf4E3sQ',
    },
    {
      name: 'Lunges',
      met: '4.1',
      mph: 0,
      rpm: '20',
      type: 'Exercise',
      id: 'VtXex8fuXYqBPoJPbfrt',
    },
    {
      type: 'Exercise',
      name: 'Tai chi, qi gong',
      rpm: '30',
      mph: 0,
      met: '3',
      id: 'ZKYTJSWf5GYlAJAzGrxh',
    },
    {
      mph: 0,
      met: '3.5',
      name: 'Band Pull Under',
      type: 'Brunch Body',
      rpm: '27.2',
      id: 'afhXwwl5hI9zcHai4SH2',
    },
    {
      name: 'Skating',
      mph: 0,
      rpm: 0,
      type: 'Cardio',
      met: '7',
      id: 'b8H3QeTppM42GFglxZuN',
    },
    {
      met: '8.5',
      rpm: 0,
      type: 'Cardio',
      mph: 0,
      name: 'Spin Class',
      id: 'bPqVHJqntskFiqaexAPa',
    },
    {
      mph: 0,
      name: 'Band Triceps Extension',
      rpm: '27.2',
      met: '3.5',
      type: 'Brunch Body',
      id: 'bsCDCINdnql4CSqz71WF',
    },
    {
      met: '9.5',
      mph: '4',
      type: 'Cardio',
      rpm: 0,
      name: 'Swimming - Backstroke (Competition)',
      id: 'dk3JN2TpCvFd2iIQlfRj',
    },
    {
      rpm: 0,
      mph: 0,
      name: 'Beach Volleyball',
      type: 'Sport',
      met: '8',
      id: 'dldOOUMyhgfYZ193jjyA',
    },
    {
      met: '6.5',
      type: 'Exercise',
      mph: 0,
      name: 'Zumba',
      rpm: 0,
      id: 'ebA7ND0FuR4hF0fUtJjy',
    },
    {
      name: 'Running (12-8 min/mile)',
      met: '9.66',
      rpm: 0,
      mph: '6',
      type: 'Cardio',
      id: 'f6GDQwffCic2JSoEjO6i',
    },
    {
      met: '5',
      mph: 0,
      name: 'Cricket',
      type: 'Sport',
      rpm: 0,
      id: 'fQ5dn7KSILf7H7bjgqjd',
    },
    {
      mph: 0,
      name: 'Wall Pushup',
      type: 'Brunch Body',
      rpm: '27.2',
      met: '3.5',
      id: 'gF5FzXSxjId7BkQXYMl6',
    },
    {
      name: 'Band Pull Apart Behind Back',
      type: 'Brunch Body',
      mph: 0,
      met: '3.5',
      rpm: '27.2',
      id: 'hcTHiyM79945VgwEZiGM',
    },
    {
      rpm: 0,
      type: 'Sport',
      mph: 0,
      met: '8',
      name: 'Basketball, Indoor',
      id: 'jPM8Y552mXdtWQK3dh7D',
    },
    {
      met: '9.3',
      name: 'Basketball, Practice',
      rpm: 0,
      type: 'Sport',
      mph: 0,
      id: 'jROpSbDOl5DDDwS13kbT',
    },
    {
      met: '4.8',
      rpm: 0,
      mph: '3',
      name: 'Power Walking (20 min/mile)',
      type: 'Cardio',
      id: 'jlZ77YinF6UTHDUqZxA1',
    },
    {
      name: 'Pickleball',
      rpm: 0,
      met: '6',
      type: 'Sport',
      mph: 0,
      id: 'kWpAX2Z6G2i04pPXv3iz',
    },
    {
      mph: 0,
      rpm: '27.2',
      type: 'Brunch Body',
      name: 'Band Shoulder Press',
      met: '3.5',
      id: 'kzUL9YroMuq8uMpwFEBP',
    },
    {
      type: 'Sport',
      met: '4',
      name: 'Table Tennis',
      rpm: 0,
      mph: 0,
      id: 'miIQbFUmPAjyzr6PetyS',
    },
    {
      type: 'Sport',
      mph: 0,
      name: 'BJJ Sparing',
      rpm: 0,
      met: '8.3',
      id: 'nYZRWfJP4yRe6egxHZJv',
    },
    {
      rpm: 0,
      name: 'Baseball, Pitching',
      type: 'Sport',
      met: '6',
      mph: 0,
      id: 'nqu7NmO374ClReY7BYqN',
    },
    {
      name: 'Soccer',
      rpm: 0,
      type: 'Sport',
      met: '8.5',
      mph: 0,
      id: 'oBKgenEOnjIf6Jd6U2ho',
    },
    {
      type: 'Cardio',
      name: 'Swimming - Front Crawl',
      mph: '2',
      met: '5.8',
      rpm: 0,
      id: 'pHBcxpv3J744c460SlJg',
    },
    {
      met: '6',
      rpm: 0,
      type: 'Sport',
      mph: 0,
      name: 'Tennis (Doubles)',
      id: 'pflnkD1pl0fH5rxGPQ0k',
    },
    {
      met: '3',
      mph: 0,
      rpm: 0,
      type: 'Cardio',
      name: 'Surfing',
      id: 'ptMYPAjH7ynxbZ0w55bq',
    },
    {
      rpm: '30',
      met: '3',
      name: 'Hip Band Side Step',
      type: 'Brunch Body',
      mph: 0,
      id: 'qcXRYAV3nS1Gj7pjichv',
    },
    {
      met: '4.5',
      name: 'Basketball, Shoot Around',
      mph: 0,
      rpm: 0,
      type: 'Sport',
      id: 'r6WATDe9dWfxilwhatbz',
    },
    {
      met: '5.5',
      type: 'Cardio',
      name: 'Skateboarding',
      rpm: 0,
      mph: '8',
      id: 'rAEbwOdHty9YHCY0f5JS',
    },
    {
      mph: 0,
      met: '5',
      rpm: 0,
      name: 'Baseball (Game)',
      type: 'Sport',
      id: 'rQy9aOWhRsY60YwAeUE7',
    },
    {
      mph: '12',
      name: 'Rowing Stationary',
      rpm: 0,
      type: 'Cardio',
      met: '7',
      id: 'ri0knm3yoXIuRznRd3AG',
    },
    {
      rpm: 0,
      type: 'Sport',
      met: '8',
      mph: 0,
      name: 'Rock Climbing',
      id: 'ro6w02Szqm0rv4SHv03y',
    },
    {
      name: 'Field Hockey',
      mph: 0,
      met: '7.8',
      type: 'Sport',
      rpm: 0,
      id: 'sUc0iybnZRncm7eNeCzX',
    },
    {
      met: '3.5',
      rpm: '27.2',
      mph: 0,
      name: 'Band Bicep Curls W/Twist',
      type: 'Brunch Body',
      id: 'suBTFjOTd5jlgCgd3uTO',
    },
    {
      rpm: '27.2',
      met: '3.5',
      name: 'Half Cobra',
      type: 'Brunch Body',
      mph: 0,
      id: 'tDlLPUvhm3lkjkU4lkYR',
    },
    {
      met: '3.5',
      type: 'Brunch Body',
      mph: 0,
      name: 'Box Dips',
      rpm: '27.2',
      id: 'tW4xTWQrg2CvdYuJo4Ls',
    },
    {
      name: 'Boxing, Sparring',
      mph: 0,
      type: 'Sport',
      met: '10.3',
      rpm: 0,
      id: 'ugku39dUWLbhAWAeVwY6',
    },
    {
      met: '3.5',
      rpm: '27.2',
      name: 'Knee Pushup',
      type: 'Brunch Body',
      mph: 0,
      id: 'uoz3iuehLoE2C6sMUJNT',
    },
    {
      rpm: 0,
      mph: 0,
      met: '5.5',
      name: 'Boxing, Punching Bag',
      type: 'Sport',
      id: 'v0PKd4SnOeU0rEUwFBRW',
    },
    {
      rpm: 0,
      mph: 0,
      type: 'Cardio',
      met: '5',
      name: 'Windsurfing',
      id: 'vIdTwEd30h4Smif1tBGU',
    },
    {
      mph: '18',
      met: '11.325',
      name: 'Cycling (Racing)',
      rpm: 0,
      type: 'Cardio',
      id: 'vzVTJjHrJ5bPORQhPgcw',
    },
    {
      met: '9.4',
      type: 'Cardio',
      rpm: 0,
      name: 'Cross Country Skiing',
      mph: '8',
      id: 'wJAPieKrG8mwg2aJDJ5g',
    },
    {
      met: '8.5',
      type: 'Sport',
      mph: 0,
      rpm: 0,
      name: 'Racquetball',
      id: 'wJjfU2qAM1diyHNO0XPP',
    },
    {
      name: 'Softball (Game)',
      met: '5',
      rpm: 0,
      mph: 0,
      type: 'Sport',
      id: 'wq6BXXLvFBlSDbzb2qkY',
    },
    {
      rpm: '30',
      name: 'Hip Band Back Step',
      type: 'Brunch Body',
      met: '3',
      mph: 0,
      id: 'x2AJZMx7W8VdvQMuZt5c',
    },
    {
      mph: '2',
      name: 'Swimming - Breaststroke',
      type: 'Cardio',
      met: '5.3',
      rpm: 0,
      id: 'x2TQ4negEkZJmuOzOLAJ',
    },
    {
      met: '3.5',
      name: 'Bench Dips',
      type: 'Brunch Body',
      rpm: '27.2',
      mph: 0,
      id: 'xIAMV1HN1rTP22jveGl0',
    },
    {
      name: 'HIIT',
      type: 'Exercise',
      mph: 0,
      rpm: '32.5',
      met: '8',
      id: 'xYfUx2jeT5naCRluZWON',
    },
    {
      met: '8',
      name: 'Swimming - Synchronized',
      rpm: 0,
      type: 'Cardio',
      mph: 0,
      id: 'xhbNd4pxKb7OOsHqJ3kc',
    },
    {
      met: '3',
      name: 'Modified Step Through',
      type: 'Brunch Body',
      mph: 0,
      rpm: '30',
      id: 'yYn7H9ag6vyGqARWfWS1',
    },
    {
      rpm: '27.2',
      type: 'Brunch Body',
      met: '3.5',
      mph: 0,
      name: 'Band Front Raise Pull Apart',
      id: 'yszvIcW28OQ0XWv1Rvsp',
    },
    {
      mph: '3',
      name: 'Paddle Boarding',
      rpm: 0,
      met: '6',
      type: 'Cardio',
      id: 'z0VfeTj16zb14jDibrxS',
    },
    {
      name: 'Canoeing',
      mph: '3',
      type: 'Cardio',
      rpm: 0,
      met: '3.5',
      id: 'zvCFiREgYQT0SDISEZh0',
    },
    {
      met: '3.5',
      rpm: '27.2',
      mph: 0,
      type: 'Brunch Body',
      name: 'Negatives',
      id: 'zwJ6sqt4dCgbk2tCtbXs',
    },
  ],
};
