module.exports.mealsDirectory = {
  categories: [
    {
      category: 'Sweets/Other',
      id: '7dtZ4AU0fZuhkYGkng5t',
    },
    {
      category: 'Flours',
      id: '86NbbpuSmlwTF80JZOuG',
    },
    {
      category: 'Chicken',
      id: '8RjSfzHOI5e7sIetlqbI',
    },
    {
      category: 'Beef',
      id: 'AbWmI0gJ56e0bcZl3T7T',
    },
    {
      category: 'Dairy',
      id: 'DNF7Pp24SmGaZ53xNncV',
    },
    {
      category: 'Oils',
      id: 'H3E3ZkQPcbPvPsS6Nkc9',
    },
    {
      category: 'Fruits',
      id: 'HuCIOnJ6E6cWvAue9iTe',
    },
    {
      category: 'Lamb',
      id: 'Yy20o7hOYmlbJ8zlI90x',
    },
    {
      category: 'Wholegrain',
      id: 'dZzsieftet1Z4w1OFf4n',
    },
    {
      category: 'Seafood',
      id: 'hxx75DTzBWmCZ9iD3EgA',
    },
    {
      category: 'Vegetables',
      id: 'jyfO3jnD5c7FxAqT76Ux',
    },
    {
      category: 'Turkey',
      id: 'l3z0AufITVmZtkfnfYGl',
    },
    {
      category: 'Mushrooms',
      id: 'qr276ndvt0dkzxWSl0VS',
    },
    {
      category: 'Bread',
      id: 'sZCn3eeiZYDjOfpQ4vwI',
    },
    {
      category: 'Nuts/Legumes',
      id: 'vlMn3jovCQ5ead6UQU3F',
    },
    {
      category: 'Pork',
      id: 'wdCb9vhhF1LoyzL4cLiR',
    },
    {
      category: 'Condiments',
      id: 'zc9MWZ2KoTsL6I9WusWM',
    },
  ],
  meals: [
    {
      type: 'Condiments',
      cho: '0.143',
      name: 'Hummus',
      cal: 0,
      fat: '0.097',
      prt: '0.078',
      id: '029HkEc6BaSA38JJRZOQ',
    },
    {
      cal: 0,
      fat: '0.786',
      prt: '0.021',
      name: 'Aioli',
      cho: '0.021',
      type: 'Condiments',
      id: '0LLek9Izj33jibMxn5dD',
    },
    {
      prt: '0.040',
      cal: 0,
      cho: '0.299',
      name: 'Dosa',
      type: 'Bread',
      fat: '0.038',
      id: '0eJLuFaxKPkx5jLwksZn',
    },
    {
      cho: 0,
      cal: 0,
      prt: '0.178',
      name: 'Crab Meat',
      fat: '0.008',
      type: 'Seafood',
      id: '0p20dBMLf1UfPCi3bu31',
    },
    {
      cal: 0,
      fat: '0.163',
      type: 'Bread',
      name: 'Biscuit',
      prt: '0.070',
      cho: '0.450',
      id: '0qpMb9WzQTrGZwgQgEWM',
    },
    {
      name: 'Flatbread',
      cho: '0.553',
      type: 'Bread',
      cal: 0,
      fat: '0.012',
      prt: '0.091',
      id: '0xyT0n30IXWhik9LYeVZ',
    },
    {
      cho: '0.165',
      name: 'Shallot',
      type: 'Vegetables',
      cal: 0,
      prt: '0.026',
      fat: '0.001',
      id: '10g1A6JnlA3zCvwxJTI4',
    },
    {
      name: 'Corn',
      type: 'Vegetables',
      fat: '0.015',
      cho: '0.214',
      cal: 0,
      prt: '0.034',
      id: '1BIBoSxYT5YFAbjTLzsK',
    },
    {
      type: 'Bread',
      prt: '0.095',
      cal: 0,
      fat: '0.060',
      cho: '0.475',
      name: 'Challah',
      id: '1JiiMDe0zKXvK5D6CtfJ',
    },
    {
      cal: 0,
      type: 'Chicken',
      name: 'Breast',
      fat: '0.033',
      cho: 0,
      prt: '0.308',
      id: '1Ql7sfYUQuD0Rl5OMCwC',
    },
    {
      cal: 0,
      type: 'Pork',
      cho: 0,
      prt: '0.255',
      name: 'Chop',
      fat: '0.108',
      id: '1Upv3u1gWcATR63APW2E',
    },
    {
      cho: '0.120',
      type: 'Nuts/Legumes',
      fat: '0.680',
      cal: 0,
      prt: '0.140',
      name: 'Brazil',
      id: '1Y7eIRGCQEhRSCW1cvHA',
    },
    {
      cal: 0,
      prt: '0.100',
      fat: '0.014',
      cho: '0.857',
      name: 'Matzo',
      type: 'Bread',
      id: '1grQa1CUbmC1nIQwZaq1',
    },
    {
      type: 'Sweets/Other',
      name: 'Brownie',
      cho: '0.500',
      cal: 0,
      prt: '0.062',
      fat: '0.300',
      id: '1hARxmYsPrRyPiCgwSBu',
    },
    {
      cal: 0,
      prt: '0.245',
      type: 'Turkey',
      cho: 0,
      name: 'Wing',
      fat: '0.111',
      id: '1iokwCaSDyLgpgiVLx2X',
    },
    {
      cal: 0,
      name: 'Cod',
      fat: '0.008',
      type: 'Seafood',
      cho: 0,
      prt: '0.228',
      id: '1qFSGWBpsMVzjGyMwLul',
    },
    {
      type: 'Flours',
      prt: '0.081',
      fat: '0.036',
      cho: '0.770',
      cal: 0,
      name: 'Cornmeal',
      id: '2A34NmhDRDMeWfFG1UjN',
    },
    {
      cho: '0.208',
      cal: 0,
      fat: '0.002',
      type: 'Vegetables',
      prt: '0.021',
      name: 'Burdock',
      id: '2IMRNmRXcfavu83fheRx',
    },
    {
      prt: 0,
      fat: 0,
      name: 'White Sugar',
      type: 'Sweets/Other',
      cho: '1.000',
      cal: 0,
      id: '2TymvnSr0jmtGscU3gXZ',
    },
    {
      cho: '0.030',
      cal: 0,
      name: 'Wheatgrass',
      type: 'Vegetables',
      fat: '0.003',
      prt: '0.013',
      id: '2a6DVAhUlbAwrIEL9HSA',
    },
    {
      cho: '0.643',
      fat: '0.186',
      type: 'Bread',
      cal: 0,
      name: 'Croutons',
      prt: '0.107',
      id: '2wJ9Kj91TdfQMkfmnzXj',
    },
    {
      cho: '0.806',
      fat: '0.000',
      name: 'Gluten-Free',
      prt: '0.065',
      type: 'Flours',
      cal: 0,
      id: '2zlwjmfAfet6JfJauXuh',
    },
    {
      name: 'Shiitake',
      cho: '0.068',
      fat: '0.005',
      prt: '0.021',
      cal: 0,
      type: 'Mushrooms',
      id: '34jCueWGIKg6Rw0QPpOl',
    },
    {
      name: 'Raspberries',
      fat: 0,
      prt: '0.000',
      cho: '0.100',
      type: 'Fruits',
      cal: 0,
      id: '3UB40ojEYM6ryhRNfeHR',
    },
    {
      cal: 0,
      type: 'Bread',
      prt: '0.047',
      cho: '0.255',
      fat: '0.090',
      name: 'Spelt Bread',
      id: '3W3cNIY1TPbJHNp2eGp6',
    },
    {
      cal: 0,
      cho: '0.469',
      fat: '0.034',
      type: 'Bread',
      name: 'Rye Bread',
      prt: '0.084',
      id: '3oCEXYfvqivvd9ERxeaO',
    },
    {
      fat: '0.026',
      name: 'Chickpea',
      type: 'Vegetables',
      cho: '0.274',
      cal: 0,
      prt: '0.091',
      id: '3oU4UvoaxBLHQXSay9Hh',
    },
    {
      type: 'Mushrooms',
      prt: '0.031',
      cal: 0,
      fat: '0.008',
      cho: '0.054',
      name: 'Morel',
      id: '4AtodevlWjOrGG41n4rw',
    },
    {
      prt: '0.022',
      cho: '0.438',
      name: 'Gochujang',
      fat: '0.006',
      cal: 0,
      type: 'Condiments',
      id: '4mS2CsIjzuU3LHk4YCLL',
    },
    {
      fat: '0.147',
      name: 'Belgian Waffle',
      type: 'Bread',
      cho: '0.333',
      cal: 0,
      prt: '0.079',
      id: '50b9QqshbvzojbQ8dAoh',
    },
    {
      cho: '0.039',
      prt: '0.009',
      type: 'Vegetables',
      name: 'Tomato',
      cal: 0,
      fat: '0.002',
      id: '55KIuFHooXewHIHtPauL',
    },
    {
      name: 'Pan Dulce',
      type: 'Bread',
      prt: '0.094',
      cho: '0.571',
      fat: '0.116',
      cal: 0,
      id: '59xkXL1U6OpwgFbPX4jP',
    },
    {
      fat: '0.003',
      prt: '0.008',
      cho: '0.030',
      name: 'Celery',
      type: 'Vegetables',
      cal: 0,
      id: '5DAqcOlTlUz9iJnD2PK8',
    },
    {
      prt: '0.118',
      cal: 0,
      type: 'Pork',
      cho: '0.015',
      name: 'Sausage',
      fat: '0.279',
      id: '5LCgHoPUHOWWSlVONVJX',
    },
    {
      cho: '0.087',
      name: 'Eggplant',
      fat: '0.002',
      cal: 0,
      prt: '0.008',
      type: 'Vegetables',
      id: '5WjavU8iSpchXjUJcfei',
    },
    {
      name: 'Broccoli',
      cal: 0,
      fat: '0.003',
      type: 'Vegetables',
      cho: '0.073',
      prt: '0.024',
      id: '5Yj8ipmZiDDD8xZJjtf7',
    },
    {
      cal: 0,
      fat: '0.064',
      name: 'Bread roll',
      cho: '0.464',
      type: 'Bread',
      prt: '0.086',
      id: '6J1Zsp9tIo1RqlcI83sX',
    },
    {
      cal: 0,
      type: 'Fruits',
      cho: '0.079',
      fat: '0.002',
      prt: '0.008',
      name: 'Melons',
      id: '6M2sEkPbppUNBwm5oh08',
    },
    {
      name: 'Olive Oil',
      cho: 0,
      type: 'Oils',
      cal: 0,
      fat: '1.000',
      prt: 0,
      id: '6NmJEQdj0lCyrlfG29IA',
    },
    {
      prt: '0.238',
      type: 'Seafood',
      cho: 0,
      name: 'Canned Tuna',
      cal: 0,
      fat: '0.030',
      id: '6OFzO7IEgkT7DIwwLuPz',
    },
    {
      fat: '0.282',
      type: 'Nuts/Legumes',
      cho: '0.518',
      name: 'Coconut',
      cal: 0,
      prt: '0.032',
      id: '6aO9g7kJ7XJDs8k4CCKb',
    },
    {
      name: 'Scallion Pancake',
      fat: '0.044',
      type: 'Bread',
      prt: '0.040',
      cal: 0,
      cho: '0.290',
      id: '6bMnIlTUocPfWSo2YujT',
    },
    {
      cal: 0,
      type: 'Turkey',
      prt: '0.282',
      cho: '0.001',
      name: 'Whole',
      fat: '0.058',
      id: '6cvG19QefeVm2P9rkn8m',
    },
    {
      type: 'Bread',
      cho: '0.275',
      prt: '0.065',
      cal: 0,
      fat: '0.098',
      name: 'Pancake',
      id: '6r97X7lRGXyiWirDamdp',
    },
    {
      cho: '0.021',
      cal: 0,
      prt: '0.021',
      name: 'Portobello',
      fat: '0.004',
      type: 'Mushrooms',
      id: '6ttn1MYQrcPTYeAn1xc6',
    },
    {
      name: 'Sweet Potato',
      prt: '0.020',
      cho: '0.211',
      cal: 0,
      fat: '0.002',
      type: 'Vegetables',
      id: '6wDn8BZyo7Ys9QWnYv4y',
    },
    {
      cho: '0.137',
      name: 'Apple',
      type: 'Fruits',
      cal: 0,
      fat: '0.002',
      prt: '0.003',
      id: '6wLY0HAQgZLwQWoIqciX',
    },
    {
      cho: '0.180',
      cal: 0,
      fat: '0.010',
      type: 'Vegetables',
      name: 'Ginger',
      prt: '0.020',
      id: '6zx5eE6uqYEHGw9kF5ZP',
    },
    {
      type: 'Bread',
      fat: '0.091',
      prt: '0.039',
      cal: 0,
      name: 'Banana Bread',
      cho: '0.402',
      id: '7QrlL2hmnSG9GReAqV3w',
    },
    {
      cal: 0,
      type: 'Fruits',
      prt: '0.008',
      name: 'Plantains',
      fat: '0.002',
      cho: '0.313',
      id: '7arTQRKY9m0zCqS4pcv9',
    },
    {
      cho: 0,
      cal: 0,
      name: 'Palm Oil',
      fat: '1.000',
      type: 'Oils',
      prt: 0,
      id: '7lk8RqMAUgOhV7c2a1V8',
    },
    {
      prt: '0.050',
      cho: '0.667',
      name: 'Cookie',
      cal: 0,
      type: 'Sweets/Other',
      fat: '0.247',
      id: '7wJldsuW1NGZJj2HbZUF',
    },
    {
      cal: 0,
      prt: '0.018',
      fat: '0.004',
      name: 'Bamboo Shoot',
      cho: '0.032',
      type: 'Vegetables',
      id: '7zYNGGurXrnLLN6z2eof',
    },
    {
      fat: '0.023',
      type: 'Bread',
      name: 'Sourdough Bread',
      cal: 0,
      cho: '0.516',
      prt: '0.108',
      id: '8HH7mZPc93BaebScvkX1',
    },
    {
      name: 'Buckwheat',
      cho: '0.708',
      prt: '0.125',
      type: 'Flours',
      cal: 0,
      fat: '0.031',
      id: '8ICjVC4ysSJZmdf2Vl0p',
    },
    {
      cal: 0,
      prt: '0.100',
      name: 'Pretzel',
      type: 'Bread',
      fat: '0.029',
      cho: '0.821',
      id: '8NuXIJGHpHvBm4FY8wAh',
    },
    {
      name: 'Macadamia',
      fat: '0.750',
      prt: '0.079',
      cal: 0,
      type: 'Nuts/Legumes',
      cho: '0.139',
      id: '8Tpo2WMM7Wn4316ftijk',
    },
    {
      name: 'Squash',
      type: 'Vegetables',
      fat: '0.004',
      prt: '0.011',
      cho: '0.038',
      cal: 0,
      id: '8VkQce1PbXoqgnu7Wjt3',
    },
    {
      name: 'Blue Cheese',
      cal: 0,
      fat: '0.289',
      cho: '0.218',
      prt: '0.025',
      type: 'Dairy',
      id: '8ekRdSFNPekMCKiY6bRC',
    },
    {
      type: 'Sweets/Other',
      prt: '0.081',
      fat: '0.229',
      cho: '0.471',
      name: 'Pastry',
      cal: 0,
      id: '8jweQK9m4RKRdSpXFJEE',
    },
    {
      cal: 0,
      fat: '0.218',
      name: 'Belly',
      cho: 0,
      prt: '0.232',
      type: 'Pork',
      id: '8mel9tUZAmEJFAvWTMKb',
    },
    {
      prt: '0.078',
      name: 'Roti',
      fat: '0.093',
      type: 'Bread',
      cho: '0.450',
      cal: 0,
      id: '8zFVUhRHq5gi0w7Ty10c',
    },
    {
      fat: '0.005',
      cal: 0,
      prt: '0.076',
      cho: '0.205',
      name: 'Black-eyed Pea',
      type: 'Vegetables',
      id: '9HVXWsKQTcrHJuTfjtUe',
    },
    {
      fat: '0.679',
      name: 'Pine',
      cho: '0.132',
      prt: '0.139',
      cal: 0,
      type: 'Nuts/Legumes',
      id: '9aduAtIQoqFJd4pevOHs',
    },
    {
      fat: '0.500',
      cal: 0,
      type: 'Wholegrain',
      prt: '0.171',
      name: 'Sesame Seed',
      cho: '0.261',
      id: 'ASIfhT2Vf1TQUiWnL9OT',
    },
    {
      cal: 0,
      name: 'Brioche',
      type: 'Bread',
      fat: '0.169',
      cho: '0.390',
      prt: '0.083',
      id: 'AajR4u60JbxSbflBwE9m',
    },
    {
      cho: '0.038',
      name: 'Spinach',
      fat: '0.003',
      type: 'Vegetables',
      prt: '0.029',
      cal: 0,
      id: 'AcUjMxI13ll2J9YtTcCS',
    },
    {
      type: 'Vegetables',
      cal: 0,
      fat: '0.002',
      prt: '0.018',
      name: 'Scallion',
      cho: '0.073',
      id: 'AtwaFGFtfeBAQ1WrXVpz',
    },
    {
      name: 'Oyster',
      cal: 0,
      prt: '0.188',
      fat: '0.048',
      type: 'Seafood',
      cho: '0.100',
      id: 'BACPWq8RCUeLD9Rg8Zdo',
    },
    {
      type: 'Wholegrain',
      name: 'Oats',
      cho: '0.659',
      fat: '0.063',
      cal: 0,
      prt: '0.129',
      id: 'BCMa5gj4wN6JyauEXFDz',
    },
    {
      prt: '0.195',
      cho: '0.156',
      fat: '0.500',
      cal: 0,
      name: 'Sunflower Seeds',
      type: 'Wholegrain',
      id: 'BIeXp8Lpsr7QR6H2IZQu',
    },
    {
      cal: 0,
      name: 'Maitake',
      fat: '0.001',
      prt: '0.020',
      cho: '0.070',
      type: 'Mushrooms',
      id: 'Blvf2wKj9QMS7x6FgGp0',
    },
    {
      type: 'Vegetables',
      cal: 0,
      prt: '0.018',
      fat: '0.004',
      name: 'Lemongrass',
      cho: '0.254',
      id: 'CpYPROTIaEgnlDU2GU2n',
    },
    {
      cho: '0.431',
      prt: '0.068',
      fat: '0.071',
      type: 'Bread',
      cal: 0,
      name: 'Cornbread',
      id: 'CpuF7WHefBiOfI59UFoi',
    },
    {
      type: 'Lamb',
      fat: '0.204',
      prt: '0.278',
      cal: 0,
      name: 'Chop',
      cho: 0,
      id: 'D71OSDKS4n3t9dbM230u',
    },
    {
      cal: 0,
      prt: '0.029',
      type: 'Vegetables',
      name: 'Artichoke',
      cho: '0.117',
      fat: '0.003',
      id: 'DSkfA0kXOm5O6NDxvyHb',
    },
    {
      cal: 0,
      cho: '0.483',
      prt: '0.062',
      name: 'Donut',
      type: 'Sweets/Other',
      fat: '0.233',
      id: 'DX7eiRStwCVOHw2S8wKV',
    },
    {
      fat: '0.011',
      name: 'Garlic',
      cho: '0.333',
      type: 'Vegetables',
      prt: '0.067',
      cal: 0,
      id: 'Dgn7Vj0MD8kPvzGjj9Su',
    },
    {
      fat: '0.714',
      prt: '0.007',
      type: 'Condiments',
      cho: '0.007',
      cal: 0,
      name: 'Mayonnaise',
      id: 'E6aA2W2Z2xTPv1bsyYgN',
    },
    {
      cho: '0.483',
      name: 'Brown Bread',
      cal: 0,
      fat: '0.031',
      type: 'Bread',
      prt: '0.107',
      id: 'EC9w0L2f6ShWRd9E4Wdc',
    },
    {
      name: 'Tenderloin',
      type: 'Pork',
      cal: 0,
      prt: '0.259',
      cho: 0,
      fat: '0.040',
      id: 'EMBLc4u1M9466HGmMtGA',
    },
    {
      type: 'Condiments',
      name: 'Tahini',
      cho: '0.213',
      cal: 0,
      fat: '0.533',
      prt: '0.173',
      id: 'EYpmzvoHnN8TW01Wl44E',
    },
    {
      fat: '0.000',
      cho: '0.036',
      prt: '0.036',
      type: 'Mushrooms',
      cal: 0,
      name: 'White Button',
      id: 'FHUW71i2pnlZYeUKLmIB',
    },
    {
      fat: '0.006',
      name: 'Barbecue Sauce',
      prt: '0.006',
      cal: 0,
      cho: '0.412',
      type: 'Condiments',
      id: 'FJAOV9Z7jUZ7lcaroaXS',
    },
    {
      name: 'Lobster',
      type: 'Seafood',
      cho: '0.032',
      prt: '0.259',
      fat: '0.019',
      cal: 0,
      id: 'FOJh7YW6cZM7nY4tNqou',
    },
    {
      type: 'Fruits',
      cho: '0.746',
      cal: 0,
      prt: '0.028',
      name: 'Dates',
      fat: '0.000',
      id: 'FYNCR0gl4OqXrndJOMx1',
    },
    {
      type: 'Fruits',
      prt: '0.005',
      cho: '0.133',
      cal: 0,
      name: 'Pineapples',
      fat: '0.001',
      id: 'FirhYAoOzwjv0z2fEJhA',
    },
    {
      cho: '0.133',
      cal: 0,
      fat: '0.733',
      name: 'Pecans',
      type: 'Nuts/Legumes',
      prt: '0.067',
      id: 'G952T6356j4gxNWdgM7J',
    },
    {
      cal: '0',
      fat: '0.224',
      name: 'New York Strip',
      cho: 0,
      prt: '0.259',
      type: 'Beef',
      id: 'GDTm8e7OkKQrTGANoQ1S',
    },
    {
      prt: '0.204',
      name: 'Shoulder',
      cal: 0,
      cho: 0,
      type: 'Lamb',
      fat: '0.054',
      id: 'GFhd3PrnTONMvARhyqps',
    },
    {
      type: 'Flours',
      cal: 0,
      fat: '0.025',
      prt: '0.133',
      name: 'Whole Wheat',
      cho: '0.717',
      id: 'GPHUSf6s8DXt2q3qVGi4',
    },
    {
      type: 'Bread',
      fat: '0.165',
      cal: 0,
      cho: '0.388',
      name: 'Brioche Bun',
      prt: '0.084',
      id: 'GYGNed2UCeldtbksPylQ',
    },
    {
      fat: '0.024',
      cho: '0.524',
      cal: 0,
      prt: '0.036',
      type: 'Nuts/Legumes',
      name: 'Chestnuts',
      id: 'HLwaljut2ZgvYTogLbSI',
    },
    {
      cho: '0.027',
      fat: '0.004',
      prt: '0.012',
      type: 'Vegetables',
      cal: 0,
      name: 'Zucchini',
      id: 'HnANhVT9mJAabIhFUKmR',
    },
    {
      name: 'Turnip',
      prt: '0.007',
      type: 'Vegetables',
      cal: 0,
      fat: '0.001',
      cho: '0.051',
      id: 'IbpsTCd1eTV3jbmORuN3',
    },
    {
      cal: 0,
      fat: '0.233',
      name: 'American Cheese',
      cho: '0.086',
      prt: '0.171',
      type: 'Dairy',
      id: 'IoeCaAvoUNn6qNPBicPl',
    },
    {
      cal: 0,
      type: 'Condiments',
      cho: '0.483',
      name: 'Mirin',
      fat: '0.000',
      prt: '0.003',
      id: 'IpKO9V3ENAs9zqQD5q9j',
    },
    {
      prt: '0.259',
      cho: 0,
      type: 'Beef',
      fat: '0.176',
      name: 'Filet Mignon',
      cal: 0,
      id: 'JdMwUDFY3Sse96NT8qEn',
    },
    {
      name: 'Heavy Cream',
      type: 'Dairy',
      cho: '0.027',
      fat: '0.367',
      prt: '0.027',
      cal: 0,
      id: 'Jksfcw5v7sSTijmY5QRC',
    },
    {
      prt: '0.070',
      type: 'Sweets/Other',
      name: 'Tortilla Chips',
      cal: 0,
      cho: '0.667',
      fat: '0.207',
      id: 'JpYf4qXPMtNqqrkO2jAr',
    },
    {
      name: 'Scone',
      cal: 0,
      prt: '0.061',
      fat: '0.139',
      type: 'Bread',
      cho: '0.487',
      id: 'JpyRbkGsq7pvlAz3t6Xl',
    },
    {
      fat: '0.170',
      cal: 0,
      prt: '0.170',
      type: 'Pork',
      cho: 0,
      name: 'Shoulder',
      id: 'K1jdBNXPRRMNwU14djES',
    },
    {
      fat: '0.003',
      type: 'Vegetables',
      cho: '0.069',
      cal: 0,
      name: 'Snow pea',
      prt: '0.033',
      id: 'KD1R5JjMil6Nl3379AqW',
    },
    {
      prt: 0,
      name: 'Peanut Oil',
      cal: 0,
      fat: '1.000',
      type: 'Oils',
      cho: 0,
      id: 'KXIq2ZTKQtYbCKkDULHV',
    },
    {
      cho: 0,
      name: 'Tuna Steak',
      type: 'Seafood',
      prt: '0.289',
      cal: 0,
      fat: '0.006',
      id: 'KY59DPVoQ4rkiC7AMTMV',
    },
    {
      type: 'Mushrooms',
      cal: 0,
      cho: '0.754',
      prt: '0.123',
      fat: '0.009',
      name: 'Black Trumpet',
      id: 'L4wnvioy2qXqMjDy22tS',
    },
    {
      cho: '0.156',
      name: 'Crêpe',
      type: 'Bread',
      cal: 0,
      prt: '0.059',
      fat: '0.083',
      id: 'LL5Z12y1gF4x1dOfWkWB',
    },
    {
      cho: '0.967',
      name: 'Brown Sugar',
      cal: 0,
      fat: 0,
      prt: 0,
      type: 'Sweets/Other',
      id: 'LMv56h40PKZPa5MQ4YIG',
    },
    {
      cho: '0.200',
      fat: '0.004',
      type: 'Vegetables',
      name: 'Fava Bean',
      prt: '0.076',
      cal: 0,
      id: 'LWqpQG9YiCsbAm2MOEPE',
    },
    {
      name: 'Clams',
      cho: '0.052',
      fat: '0.020',
      cal: 0,
      prt: '0.259',
      type: 'Seafood',
      id: 'LqXhgtbgkMnyde6CuUSz',
    },
    {
      prt: '0.104',
      cho: '0.760',
      fat: '0.010',
      cal: 0,
      type: 'Flours',
      name: 'All Purpose',
      id: 'LwvvgSulB2fkk0DeEwn5',
    },
    {
      cal: 0,
      fat: '0.000',
      prt: '0.133',
      name: 'Sprouted Bread',
      type: 'Bread',
      cho: '0.350',
      id: 'LycAfnMb3Z0q6ePAs6Ph',
    },
    {
      cal: 0,
      cho: '0.066',
      prt: '0.013',
      type: 'Vegetables',
      fat: '0.105',
      name: 'Olive',
      id: 'M6Qg7Lz1IoJcCt7xro9j',
    },
    {
      name: 'Hamburger 90/10',
      cho: 0,
      type: 'Beef',
      cal: 0,
      prt: '0.285',
      fat: '0.120',
      id: 'MRzW9wsSmdv9NotnDivK',
    },
    {
      cho: '0.557',
      cal: 0,
      fat: '0.342',
      type: 'Wholegrain',
      name: 'Popcorn',
      prt: '0.076',
      id: 'MXY3c6gAxUAD5VrSssRP',
    },
    {
      fat: '0.002',
      cal: 0,
      prt: '0.008',
      name: 'Leek',
      cho: '0.076',
      type: 'Vegetables',
      id: 'MXeDULvM91hee8rGW62b',
    },
    {
      type: 'Chicken',
      cal: 0,
      name: 'Whole',
      cho: 0,
      prt: '0.279',
      fat: '0.138',
      id: 'MsqHvPVpEWHRAdqGPXMh',
    },
    {
      name: 'Chiles',
      fat: '0.004',
      cho: '0.089',
      cal: 0,
      prt: '0.018',
      type: 'Vegetables',
      id: 'NB1Sa5UZWw0jSXU4LQtt',
    },
    {
      name: 'Teacake',
      cho: '0.515',
      fat: '0.040',
      type: 'Bread',
      cal: 0,
      prt: '0.071',
      id: 'NJWzqHKbJAUEfUJyjNON',
    },
    {
      cal: 0,
      prt: '0.143',
      type: 'Nuts/Legumes',
      fat: '0.429',
      name: 'Pistachio',
      cho: '0.286',
      id: 'NeysxG5xr3F19HrR7kzY',
    },
    {
      fat: '0.029',
      name: 'Tortilla Corn',
      type: 'Bread',
      cho: '0.458',
      prt: '0.058',
      cal: 0,
      id: 'NheY2Nv7S7WDFhyS17Ju',
    },
    {
      cho: '0.463',
      fat: '0.098',
      cal: 0,
      name: 'Tortilla Wheat',
      prt: '0.098',
      type: 'Bread',
      id: 'NrGk6xJHJK0wdQrZr7Pk',
    },
    {
      cho: '0.353',
      cal: 0,
      name: 'Relish',
      fat: '0.007',
      type: 'Condiments',
      prt: '0.007',
      id: 'Nv8Auq9IEAppHasnbRTt',
    },
    {
      name: 'Soy Sauce',
      type: 'Condiments',
      fat: '0.006',
      cho: '0.050',
      cal: 0,
      prt: '0.081',
      id: 'OBehCvJWZTStM6wfR7ex',
    },
    {
      fat: '0.188',
      type: 'Beef',
      cal: 0,
      prt: '0.247',
      cho: 0,
      name: 'Rib Eye Steak',
      id: 'OTvVGOSvp3zAVflkTk8l',
    },
    {
      fat: '0.001',
      cal: 0,
      name: 'Limes',
      type: 'Fruits',
      cho: '0.106',
      prt: '0.007',
      id: 'OvNFcMEmo8iF02Vwdwtu',
    },
    {
      name: 'Cauliflower',
      cho: '0.042',
      cal: 0,
      prt: '0.019',
      type: 'Vegetables',
      fat: '0.005',
      id: 'Ow3qw18btBota6kphjNO',
    },
    {
      fat: '0.241',
      prt: '0.167',
      cho: 0,
      name: 'Wing',
      type: 'Chicken',
      cal: 0,
      id: 'PAIzAcXgk2vGsj5nZTa4',
    },
    {
      name: 'Cremini',
      prt: '0.025',
      cho: '0.043',
      type: 'Mushrooms',
      fat: '0.001',
      cal: 0,
      id: 'PFR0IxpCiV7Z8CitObBw',
    },
    {
      prt: '0.003',
      name: 'Fiddlehead',
      fat: '0.001',
      cal: 0,
      cho: '0.110',
      type: 'Vegetables',
      id: 'PXBblXBFzAZ6aZFMF2Je',
    },
    {
      cal: 0,
      fat: '0.004',
      prt: '0.091',
      cho: '0.202',
      type: 'Vegetables',
      name: 'Lentil',
      id: 'PYaVR1EoKnCiX7v4oN5x',
    },
    {
      fat: '0.000',
      type: 'Fruits',
      prt: '0.000',
      name: 'Blueberries',
      cal: 0,
      cho: '0.143',
      id: 'PYj1mLxeRp2kxEyfC77P',
    },
    {
      type: 'Vegetables',
      cho: '0.079',
      name: 'Green Bean',
      cal: 0,
      prt: '0.019',
      fat: '0.002',
      id: 'PowEVe4l7whrZJ5iSWmS',
    },
    {
      prt: '0.032',
      cho: '0.188',
      cal: 0,
      name: 'Corn',
      fat: '0.013',
      type: 'Wholegrain',
      id: 'PpisSVFFr8dgxm7gBYYB',
    },
    {
      fat: '0.022',
      prt: '0.125',
      type: 'Wholegrain',
      cho: '0.734',
      cal: 0,
      name: 'Barley',
      id: 'Q5eKbAzFT1WkHkb21G5X',
    },
    {
      type: 'Vegetables',
      prt: '0.024',
      cal: 0,
      name: 'Watercress',
      cho: '0.012',
      fat: '0.000',
      id: 'QSWK8nH8y2ohBUNTYqBy',
    },
    {
      cal: 0,
      cho: '0.029',
      prt: '0.343',
      fat: '0.343',
      type: 'Pork',
      name: 'Bacon',
      id: 'QTn64UtEjZ2sy1vgkzoh',
    },
    {
      type: 'Condiments',
      fat: '0.033',
      name: 'Mustard',
      prt: '0.040',
      cho: '0.060',
      cal: 0,
      id: 'Qh52glXwvikmRctKtXlO',
    },
    {
      fat: '0.196',
      cho: 0,
      prt: '0.179',
      type: 'Pork',
      name: 'Ground',
      cal: 0,
      id: 'QkshEut1ZQ1twqja1PPE',
    },
    {
      prt: '0.015',
      cal: 0,
      type: 'Mushrooms',
      fat: '0.006',
      name: 'Chanterelle',
      cho: '0.069',
      id: 'R6E0lwmkgiLirxAFiphT',
    },
    {
      cal: 0,
      type: 'Vegetables',
      name: 'Jalapeño',
      fat: '0.007',
      prt: '0.007',
      cho: '0.064',
      id: 'R6vRG0I5IbDC5ncJUzC1',
    },
    {
      prt: '0.006',
      name: 'Persimmons',
      cho: '0.185',
      type: 'Fruits',
      cal: 0,
      fat: '0.002',
      id: 'RHNeyu4CjXQ1t03iHMbJ',
    },
    {
      fat: '0.643',
      prt: '0.154',
      cal: 0,
      name: 'Hazelnuts',
      type: 'Nuts/Legumes',
      cho: '0.179',
      id: 'Rlfbn1dzywwOHKgVkBEp',
    },
    {
      fat: '0.022',
      cho: '0.711',
      prt: '0.133',
      name: 'Porcini',
      type: 'Mushrooms',
      cal: 0,
      id: 'RoWdVYjDN17x7jyfPBBh',
    },
    {
      fat: '0.057',
      name: 'Panettone',
      cho: '0.558',
      type: 'Bread',
      prt: '0.057',
      cal: 0,
      id: 'SHcPmQADaZk2Uf1rpZEw',
    },
    {
      fat: '0.004',
      prt: '0.018',
      type: 'Vegetables',
      cal: 0,
      name: 'Habanero',
      cho: '0.089',
      id: 'TRTG2VfbdYMdDECU7mvf',
    },
    {
      cho: 0,
      type: 'Beef',
      prt: '0.272',
      name: 'Top Sirloin',
      fat: '0.141',
      cal: 0,
      id: 'TqyKpLtrMZwoneRpeQfh',
    },
    {
      cal: 0,
      cho: '0.055',
      name: 'Cream Cheese',
      prt: '0.062',
      fat: '0.345',
      type: 'Dairy',
      id: 'TsPFR5mOn1SIVs0BT7UI',
    },
    {
      name: 'Pumpernickel',
      cho: '0.469',
      fat: '0.031',
      type: 'Bread',
      prt: '0.088',
      cal: 0,
      id: 'TtPidHqemy3zlcAI9rXv',
    },
    {
      type: 'Fruits',
      fat: '0.001',
      cho: '0.077',
      name: 'Watermelon',
      cal: 0,
      prt: '0.006',
      id: 'UM4ozs7ET9Td3GxdFMgz',
    },
    {
      name: 'Baguette',
      type: 'Bread',
      fat: '0.024',
      cal: 0,
      cho: '0.519',
      prt: '0.108',
      id: 'URk4uJbgMcRXo0mYXHFf',
    },
    {
      cho: '0.757',
      type: 'Wholegrain',
      name: 'Rye',
      prt: '0.101',
      cal: 0,
      fat: '0.017',
      id: 'UyOfpNRBBLvjx3dVGBcF',
    },
    {
      name: 'Canadian White',
      cal: 0,
      prt: '0.075',
      type: 'Bread',
      fat: '0.050',
      cho: '0.500',
      id: 'V15b52Wl8TexSpHkixT4',
    },
    {
      cal: 0,
      prt: '0.027',
      fat: '0.007',
      name: 'Collard Greens',
      type: 'Vegetables',
      cho: '0.058',
      id: 'V4y4wICqP0THVvGm2ohH',
    },
    {
      type: 'Sweets/Other',
      fat: '0.246',
      name: 'Candy Bar (average)',
      cho: '0.614',
      prt: '0.075',
      cal: 0,
      id: 'VG9jvee6rOinBdNrEIWz',
    },
    {
      cho: '0.015',
      cal: 0,
      prt: '0.269',
      type: 'Dairy',
      name: 'Swiss Cheese',
      fat: '0.306',
      id: 'VH7HmAklUqDmnjK8WwRs',
    },
    {
      cho: '0.056',
      name: 'Kale',
      fat: '0.004',
      cal: 0,
      type: 'Vegetables',
      prt: '0.019',
      id: 'VO4uy6TVAJujSqpywPP9',
    },
    {
      prt: '0.008',
      cal: 0,
      cho: '0.149',
      fat: '0.004',
      name: 'Mango',
      type: 'Fruits',
      id: 'VQtntGQjLjz9WrHD7u9z',
    },
    {
      type: 'Vegetables',
      prt: '0.024',
      name: 'Heart of Palm',
      fat: '0.006',
      cal: 0,
      cho: '0.045',
      id: 'VlrEeT85kasHqnremJFA',
    },
    {
      cal: 0,
      prt: '0.125',
      type: 'Bread',
      name: 'Whole Wheat Bread',
      fat: '0.034',
      cho: '0.438',
      id: 'W2f3cM6WIupwYLagwevi',
    },
    {
      cal: 0,
      type: 'Bread',
      prt: '0.068',
      fat: '0.145',
      cho: '0.591',
      name: 'Biscotti',
      id: 'WQKUFNORVZbPckFT0Ln3',
    },
    {
      type: 'Wholegrain',
      cal: 0,
      cho: '0.748',
      fat: '0.043',
      prt: '0.109',
      name: 'Millet',
      id: 'Wgj9onuSoIQvnHXIDk9t',
    },
    {
      fat: '0.032',
      name: 'White Bread',
      type: 'Bread',
      cal: 0,
      prt: '0.089',
      cho: '0.486',
      id: 'WrD1tMzKzkX2imo2fIrb',
    },
    {
      type: 'Vegetables',
      name: 'Asparagus',
      cal: 0,
      cho: '0.041',
      prt: '0.024',
      fat: '0.003',
      id: 'Wvy9RnL6yAWcuFNu7XLn',
    },
    {
      prt: '0.000',
      fat: '0.002',
      cho: '0.100',
      type: 'Vegetables',
      name: 'Beets',
      cal: 0,
      id: 'X3nXS0n8aUmhCfjUspr0',
    },
    {
      cho: '0.125',
      type: 'Vegetables',
      prt: '0.050',
      cal: 0,
      fat: '0.025',
      name: 'Grape Leaves',
      id: 'XWCmDLNPuysaa4HGs16S',
    },
    {
      name: 'Pita',
      prt: '0.092',
      fat: '0.012',
      type: 'Bread',
      cal: 0,
      cho: '0.550',
      id: 'XpSrcvV3U3Xks3fXsRUH',
    },
    {
      type: 'Dairy',
      cal: 0,
      prt: '0.236',
      name: 'Muenster Cheese',
      cho: '0.011',
      fat: '0.304',
      id: 'Y4tSZKNFKvcbvasWXyQk',
    },
    {
      fat: '0.159',
      prt: '0.045',
      type: 'Sweets/Other',
      cal: 0,
      name: 'Muffin',
      cho: '0.531',
      id: 'YO8MGsVgHRQTfwUqKYPc',
    },
    {
      type: 'Wholegrain',
      name: 'Brown Rice',
      cho: '0.235',
      prt: '0.023',
      fat: '0.008',
      cal: 0,
      id: 'YUEUE9BdQTa3YkmOs5j4',
    },
    {
      cho: '0.049',
      fat: '0.010',
      cal: 0,
      prt: '0.034',
      name: 'Milk (1%)',
      type: 'Dairy',
      id: 'YZ2XDLwk65AY5OZL6WFn',
    },
    {
      cho: '0.100',
      prt: '0.013',
      type: 'Vegetables',
      name: 'Pearl Onion',
      cal: 0,
      fat: '0.002',
      id: 'Ys2inR3UlTTlBaik7Jm2',
    },
    {
      cho: 0,
      fat: '0.021',
      cal: 0,
      type: 'Turkey',
      prt: '0.306',
      name: 'Breast',
      id: 'Z5bA2MIMVgfwcG51ueAF',
    },
    {
      cho: 0,
      fat: '0.082',
      name: 'Flank steak',
      prt: '0.282',
      cal: 0,
      type: 'Beef',
      id: 'ZRdOGbAtVALs1WVe70vu',
    },
    {
      name: 'Leg',
      cho: 0,
      type: 'Chicken',
      cal: 0,
      prt: '0.240',
      fat: '0.089',
      id: 'a7OSDVg0oYioF7DHLsK7',
    },
    {
      cho: '0.200',
      type: 'Nuts/Legumes',
      fat: '0.500',
      cal: 0,
      prt: '0.200',
      name: 'Peanuts',
      id: 'aNSqBtOvmyBVR842y8Zu',
    },
    {
      name: 'Potato Chips',
      cho: '0.536',
      type: 'Sweets/Other',
      cal: 0,
      prt: '0.064',
      fat: '0.339',
      id: 'adFcdak5DXqIGYdgPp6r',
    },
    {
      cho: '0.216',
      name: 'Quinoa',
      type: 'Wholegrain',
      prt: '0.043',
      cal: 0,
      fat: '0.022',
      id: 'ambMmxhykS3dECbilfCO',
    },
    {
      name: 'Grapes',
      type: 'Fruits',
      cho: '0.182',
      fat: '0.002',
      prt: '0.008',
      cal: 0,
      id: 'b4XmKkKxM2i0aztTdGpF',
    },
    {
      name: 'Worcestershire',
      prt: '0.000',
      fat: '0.000',
      cal: 0,
      cho: '0.194',
      type: 'Condiments',
      id: 'bLWrTKvtMKurIrkGEOXb',
    },
    {
      name: 'Pears',
      cho: '0.152',
      type: 'Fruits',
      cal: 0,
      fat: '0.002',
      prt: '0.003',
      id: 'bUwLXVGDcdqVMLgidXbC',
    },
    {
      prt: '0.022',
      name: 'Napa Cabbage',
      fat: '0.002',
      cal: 0,
      cho: '0.011',
      type: 'Vegetables',
      id: 'bixWIf0xcwIoLkdhOEBE',
    },
    {
      cal: 0,
      prt: '0.010',
      type: 'Vegetables',
      name: 'Horseradish',
      fat: '0.005',
      cho: '0.110',
      id: 'c38RzDmmzLNAgbUbKmoE',
    },
    {
      cal: 0,
      prt: '0.026',
      fat: '0.005',
      cho: '0.071',
      type: 'Vegetables',
      name: 'Brussels Sprouts',
      id: 'cLJ43bKZDIKhiF7ApH5h',
    },
    {
      name: 'Potato',
      cho: '0.214',
      fat: '0.001',
      prt: '0.025',
      cal: 0,
      type: 'Vegetables',
      id: 'cLPvgOyIcb37Rt8YFMI7',
    },
    {
      fat: '1.000',
      cho: 0,
      type: 'Oils',
      cal: 0,
      prt: 0,
      name: 'Avocado Oil',
      id: 'cMlBnazZqV1vBDd5XC9b',
    },
    {
      fat: '0.093',
      name: 'Pizza Slice',
      cho: '0.336',
      type: 'Sweets/Other',
      prt: '0.112',
      cal: 0,
      id: 'cpNIDMs1mZKUxEjA7Q68',
    },
    {
      type: 'Vegetables',
      name: 'Fennel',
      cal: 0,
      fat: '0.002',
      cho: '0.074',
      prt: '0.013',
      id: 'czRy5ikkQdOFBQlXH4O1',
    },
    {
      type: 'Dairy',
      cho: '0.032',
      name: 'Cheddar Cheese',
      prt: '0.232',
      fat: '0.336',
      cal: 0,
      id: 'dNTa60ALWbv7duZatne2',
    },
    {
      fat: '0.039',
      cal: 0,
      name: 'Breakfast Cereal (average)',
      prt: '0.047',
      cho: '0.861',
      type: 'Sweets/Other',
      id: 'deXHNWXw0ilZwhlGXLsq',
    },
    {
      fat: '0.095',
      prt: '0.239',
      cal: 0,
      name: 'Thigh',
      cho: '0.004',
      type: 'Turkey',
      id: 'djJgxPEYhpQIoqUvlzv2',
    },
    {
      name: 'Sriracha',
      type: 'Condiments',
      cal: 0,
      fat: '0.010',
      prt: '0.021',
      cho: '0.185',
      id: 'e7pgAlEmwqcZEGVWg81C',
    },
    {
      prt: '0.129',
      cho: '0.253',
      fat: '0.059',
      type: 'Condiments',
      cal: 0,
      name: 'Miso',
      id: 'eGCZIKCD2K5s4Nx4k1wi',
    },
    {
      cho: '0.229',
      cal: 0,
      name: 'Bananas',
      type: 'Fruits',
      prt: '0.011',
      fat: '0.003',
      id: 'efqE8vvEXgF6kqeQM2Iy',
    },
    {
      fat: '0.650',
      cho: '0.150',
      cal: 0,
      type: 'Nuts/Legumes',
      name: 'Walnut',
      prt: '0.150',
      id: 'epvu85oeBajY94MhmMZ9',
    },
    {
      fat: '0.225',
      prt: '0.225',
      name: 'Mozzarella Cheese',
      cho: '0.021',
      cal: 0,
      type: 'Dairy',
      id: 'evcZFLPzxaV7TeMZe0Zr',
    },
    {
      prt: '0.143',
      name: 'Feta Cheese',
      cal: 0,
      cho: '0.043',
      type: 'Dairy',
      fat: '0.214',
      id: 'eyK0KzFRwCFUeFBfQnvR',
    },
    {
      type: 'Beef',
      cal: 0,
      fat: '0.174',
      cho: 0,
      prt: '0.270',
      name: 'Hamburger 80/20',
      id: 'f5vImbATt2uP96VkCUvZ',
    },
    {
      cal: 0,
      fat: '0.110',
      type: 'Vegetables',
      name: 'Wasabi',
      cho: '0.460',
      prt: '0.025',
      id: 'f70bYINbbYeAZSALKXhh',
    },
    {
      name: 'Chutney',
      type: 'Condiments',
      cal: 0,
      prt: '0.047',
      fat: '0.082',
      cho: '0.100',
      id: 'fLDsClkOO8yM11zrfbFh',
    },
    {
      fat: '0.138',
      cho: 0,
      cal: 0,
      prt: '0.238',
      name: 'Thigh',
      type: 'Chicken',
      id: 'fwSAHjWHqSaKg5H3U2L0',
    },
    {
      name: 'Cake',
      fat: '0.009',
      type: 'Flours',
      cho: '0.781',
      prt: '0.080',
      cal: 0,
      id: 'fyJKXC5EL4p2AplVCmoy',
    },
    {
      cal: 0,
      name: 'Peas',
      fat: '0.002',
      prt: '0.054',
      type: 'Vegetables',
      cho: '0.156',
      id: 'gJqAd148p9ZT8yj66zQi',
    },
    {
      type: 'Vegetables',
      cho: '0.036',
      name: 'Cucumber',
      cal: 0,
      fat: '0.001',
      prt: '0.006',
      id: 'geRfvklWi0Bz4nD44IbV',
    },
    {
      cho: '0.039',
      name: 'Fish Sauce',
      type: 'Condiments',
      fat: '0.000',
      prt: '0.050',
      cal: 0,
      id: 'gz47v5atLYf78fufLkZE',
    },
    {
      type: 'Vegetables',
      name: 'Swiss Chard',
      cal: 0,
      fat: '0.001',
      prt: '0.019',
      cho: '0.041',
      id: 'h3ExY3xArP49KQtCgQBt',
    },
    {
      type: 'Wholegrain',
      cal: 0,
      fat: '0.006',
      prt: '0.036',
      cho: '0.202',
      name: 'Buckwheat',
      id: 'iLbqIGqgvtdODMwSfJxD',
    },
    {
      type: 'Oils',
      cho: 0,
      prt: 0,
      cal: 0,
      name: 'Sesame Oil',
      fat: '1.000',
      id: 'ijgTn3mLusEhpnFLocis',
    },
    {
      fat: '0.002',
      cho: '0.133',
      name: 'Arrowroot',
      cal: 0,
      prt: '0.043',
      type: 'Flours',
      id: 'iqHqgVnm2pRtE2gu1fH5',
    },
    {
      type: 'Wholegrain',
      fat: '0.026',
      cal: 0,
      prt: '0.135',
      cho: '0.731',
      name: 'Teff',
      id: 'iwpCX05orQvNuhUiBVSs',
    },
    {
      type: 'Vegetables',
      cho: '0.083',
      prt: '0.007',
      fat: '0.002',
      name: 'Carrot',
      cal: 0,
      id: 'j8ECxfVHO9G2gYSMWc8c',
    },
    {
      prt: '0.007',
      cal: 0,
      name: 'Pumpkin',
      cho: '0.049',
      type: 'Vegetables',
      fat: '0.001',
      id: 'jUBgqxoNAvh51CKNpeuG',
    },
    {
      prt: '0.220',
      fat: '0.123',
      cho: 0,
      type: 'Seafood',
      name: 'Salmon',
      cal: 0,
      id: 'jYsA4pvB7FCRJqbkO0Kr',
    },
    {
      cho: '0.625',
      type: 'Flours',
      prt: '0.156',
      fat: '0.044',
      name: 'Psyllium Husk',
      cal: 0,
      id: 'jfbsRNz969q01zx7I6U3',
    },
    {
      fat: '0.031',
      name: 'Potato Bread',
      type: 'Bread',
      cho: '0.469',
      cal: 0,
      prt: '0.125',
      id: 'k290ggUdB2Jb0bh4j2Oz',
    },
    {
      cal: 0,
      name: 'Blackberries',
      type: 'Fruits',
      fat: '0.000',
      prt: '0.015',
      cho: '0.092',
      id: 'k3Hp6FZCYJ4pI2aodR3J',
    },
    {
      name: 'Bell Pepper',
      type: 'Vegetables',
      fat: '0.002',
      cho: '0.066',
      prt: '0.010',
      cal: 0,
      id: 'k4DvvnZbwCmTcb3TGSxe',
    },
    {
      fat: '0.004',
      name: 'Lemons',
      type: 'Fruits',
      prt: '0.011',
      cho: '0.093',
      cal: 0,
      id: 'kHo1zIY6NSPCRfn6csMS',
    },
    {
      cal: 0,
      name: 'Leg',
      type: 'Turkey',
      fat: '0.095',
      prt: '0.284',
      cho: 0,
      id: 'kKoRCQuBfG3tfV6FBwCb',
    },
    {
      fat: '0.009',
      prt: '0.009',
      cho: '0.059',
      type: 'Vegetables',
      cal: 0,
      name: 'Tomatillo',
      id: 'kdAtqI9G5TaEnmfxhiM6',
    },
    {
      fat: '0.004',
      cho: '0.061',
      prt: '0.033',
      type: 'Mushrooms',
      name: 'Oyster',
      cal: 0,
      id: 'ke66P7Ofo5yZ4Wn3PlPM',
    },
    {
      cho: '0.145',
      fat: '0.006',
      prt: '0.012',
      name: 'Kiwi',
      cal: 0,
      type: 'Fruits',
      id: 'lY3mN6ua6tiwiUvIXc4j',
    },
    {
      type: 'Vegetables',
      cal: 0,
      name: 'Chives',
      cho: '0.042',
      fat: '0.008',
      prt: '0.033',
      id: 'lbf8ekmjvPK4SfLekNRB',
    },
    {
      cal: 0,
      prt: '0.007',
      cho: '0.077',
      name: 'Strawberries',
      fat: '0.003',
      type: 'Fruits',
      id: 'ljSfNzfXThBLa0X0Yiu1',
    },
    {
      cal: 0,
      prt: '0.008',
      cho: '0.114',
      fat: '0.003',
      type: 'Fruits',
      name: 'Plums',
      id: 'lxl3tEKawh8NLerR6pB3',
    },
    {
      type: 'Lamb',
      fat: '0.129',
      cal: 0,
      prt: '0.282',
      name: 'Shank',
      cho: 0,
      id: 'm7uUv6kTjf5lK5abCoa1',
    },
    {
      cal: 0,
      type: 'Dairy',
      prt: '0.033',
      fat: '0.107',
      cho: '0.047',
      name: 'Half & Half',
      id: 'mImrohG218zxWPlTm761',
    },
    {
      cal: 0,
      prt: '0.013',
      name: 'Cabbage',
      fat: '0.001',
      cho: '0.055',
      type: 'Vegetables',
      id: 'mPxFfkNsQvyuaAuBCnhm',
    },
    {
      name: 'Eggs',
      prt: '0.126',
      fat: '0.096',
      cal: 0,
      cho: '0.008',
      type: 'Chicken',
      id: 'mfXYWY8YKkA5ds6YjGGS',
    },
    {
      type: 'Bread',
      fat: '0.100',
      name: 'Breadstick',
      prt: '0.117',
      cal: 0,
      cho: '0.683',
      id: 'muqo84FaRmeMeBfz9n6C',
    },
    {
      prt: 0,
      cal: 0,
      type: 'Oils',
      fat: '0.929',
      cho: 0,
      name: 'Coconut Oil',
      id: 'nEPOr2N1ARpFJXPre7rx',
    },
    {
      cal: 0,
      type: 'Mushrooms',
      prt: '0.020',
      name: 'Enoki',
      cho: '0.080',
      fat: '0.000',
      id: 'nFp477b1r3loOiCF7rA6',
    },
    {
      cal: 0,
      fat: '0.014',
      type: 'Flours',
      prt: '0.059',
      name: 'Rice',
      cho: '0.804',
      id: 'nZZxxP9PCapKwVkfaZHe',
    },
    {
      cho: '0.270',
      type: 'Bread',
      fat: '0.149',
      cal: 0,
      prt: '0.059',
      name: 'Potato Pancake',
      id: 'o4G73YpopP4VRIpT0hmK',
    },
    {
      prt: '0.014',
      type: 'Vegetables',
      cal: 0,
      fat: '0.002',
      cho: '0.101',
      name: 'Onion',
      id: 'oJCDbFAECUgXABzt2Zse',
    },
    {
      cal: 0,
      prt: '0.110',
      fat: '0.043',
      cho: '0.034',
      type: 'Dairy',
      name: 'Cottage Cheese',
      id: 'oXbWxRqaymQUID4ka5nx',
    },
    {
      fat: '0.008',
      type: 'Vegetables',
      cal: 0,
      cho: '0.054',
      name: 'Nori',
      prt: '0.062',
      id: 'okVXYY3IluScJIhcqRcz',
    },
    {
      prt: '0.125',
      cho: '0.313',
      name: 'Cashew',
      cal: 0,
      fat: '0.438',
      type: 'Nuts/Legumes',
      id: 'osmRmiHUMZ546JoNc2er',
    },
    {
      type: 'Wholegrain',
      prt: '0.190',
      fat: '0.430',
      cal: 0,
      name: 'Flaxseed',
      cho: '0.300',
      id: 'oz2KwVal7lQTzoFSmq4j',
    },
    {
      type: 'Bread',
      cal: 0,
      name: 'Soda bread',
      fat: '0.049',
      cho: '0.558',
      prt: '0.065',
      id: 'p36wM92woQEPuIb4gcyb',
    },
    {
      cal: 0,
      prt: '0.013',
      name: 'Parsnip',
      fat: '0.003',
      cho: '0.173',
      type: 'Vegetables',
      id: 'p7dYZDNmkymJB9PlgnqA',
    },
    {
      name: 'Lima Bean',
      cho: '0.207',
      cal: 0,
      type: 'Vegetables',
      prt: '0.080',
      fat: '0.004',
      id: 'pC1Coe46go4e42OlGU2l',
    },
    {
      type: 'Sweets/Other',
      cal: 0,
      name: 'Slice of Cake',
      cho: '0.567',
      fat: '0.179',
      prt: '0.030',
      id: 'pJ94gOZw3mqRpe7M4HZh',
    },
    {
      cal: 0,
      name: 'Bread',
      fat: '0.017',
      type: 'Flours',
      prt: '0.117',
      cho: '0.723',
      id: 'pOfTacDrt1xDAVHQbKCW',
    },
    {
      cal: 0,
      type: 'Flours',
      cho: '0.690',
      name: 'Double Zero',
      fat: '0.014',
      prt: '0.130',
      id: 'pUPb03Xx3uwqsLc06CE9',
    },
    {
      type: 'Vegetables',
      prt: '0.035',
      fat: '0.004',
      cho: '0.069',
      cal: 0,
      name: 'Snap pea',
      id: 'pW35dP7S1PkanJOiZurN',
    },
    {
      cho: '0.456',
      cal: 0,
      prt: '0.077',
      fat: '0.018',
      type: 'Bread',
      name: 'English Muffin',
      id: 'pq44U3JNS1hQm5ZdWXit',
    },
    {
      type: 'Condiments',
      fat: '0.006',
      prt: '0.011',
      cho: '0.111',
      cal: 0,
      name: 'Oyster Sauce',
      id: 'pw4oilUuxmCzi7F8zH8V',
    },
    {
      cho: 0,
      cal: 0,
      fat: '0.314',
      name: 'Ribs',
      type: 'Pork',
      prt: '0.209',
      id: 'q1aVWxGPoVYcYviLNMDF',
    },
    {
      prt: '0.009',
      cal: 0,
      fat: '0.001',
      name: 'Orange',
      type: 'Fruits',
      cho: '0.129',
      id: 'qCEjTxlLKYgChMGtPbHl',
    },
    {
      name: 'Ham',
      cal: 0,
      prt: '0.170',
      cho: '0.006',
      fat: '0.034',
      type: 'Pork',
      id: 'qGYFlWqA5NkPANTwxu40',
    },
    {
      name: 'Vegetable Oil',
      cal: 0,
      type: 'Oils',
      cho: 0,
      fat: '1.000',
      prt: 0,
      id: 'qJqsPWVx4KgyLj49zdXH',
    },
    {
      name: 'Milk (Whole)',
      cal: 0,
      prt: '0.032',
      fat: '0.032',
      cho: '0.049',
      type: 'Dairy',
      id: 'qTCCDHdM3UC9rc9fTviB',
    },
    {
      type: 'Mushrooms',
      cal: 0,
      prt: '0.020',
      name: 'King Trumpet',
      cho: '0.080',
      fat: 0,
      id: 'qhkC1Hs5XG2H1cb6UX1o',
    },
    {
      type: 'Seafood',
      cal: 0,
      name: 'Tilapia',
      fat: '0.026',
      prt: '0.259',
      cho: 0,
      id: 'qrQpJGxibXId0b2B49aT',
    },
    {
      type: 'Dairy',
      fat: '0.857',
      cho: 0,
      name: 'Butter',
      prt: '0.007',
      cal: 0,
      id: 'rQoi4yKsptA63zhkVJr2',
    },
    {
      name: 'White Rice',
      cal: 0,
      cho: '0.285',
      prt: '0.027',
      type: 'Wholegrain',
      fat: '0.003',
      id: 'rXBwP6HpPn8t3sl0XxHU',
    },
    {
      cal: 0,
      prt: '0.013',
      type: 'Condiments',
      fat: '0.367',
      cho: '0.147',
      name: 'Thousand Islands',
      id: 'rcYdBzBcAQKDU4E03p74',
    },
    {
      cal: 0,
      fat: '0.057',
      type: 'Bread',
      name: 'Naan',
      prt: '0.097',
      cho: '0.500',
      id: 'rgo0TcF57eDiDQm7HyfD',
    },
    {
      prt: '0.115',
      name: 'Sorghum',
      cho: '0.745',
      cal: 0,
      fat: '0.031',
      type: 'Wholegrain',
      id: 'sEDc9SMgBjtYGPIoG3LA',
    },
    {
      name: 'Ketchup',
      type: 'Condiments',
      cho: '0.276',
      prt: '0.012',
      fat: '0.000',
      cal: 0,
      id: 'sviOSl2QsTZbuB41h7Jw',
    },
    {
      type: 'Fruits',
      cho: '0.085',
      name: 'Avocados',
      cal: 0,
      prt: '0.020',
      fat: '0.144',
      id: 'tCNZjjENK9WylLdaoHae',
    },
    {
      prt: '0.091',
      fat: '0.026',
      name: 'Garbanzo',
      type: 'Vegetables',
      cal: 0,
      cho: '0.274',
      id: 'u8zELX7fkx18QLyZxaDI',
    },
    {
      cho: '0.181',
      type: 'Wholegrain',
      prt: '0.246',
      cal: 0,
      name: 'Pumpkin seeds',
      fat: '0.457',
      id: 'ub1EnkyqIt2STxZD3FSQ',
    },
    {
      type: 'Condiments',
      name: 'Tartar sauce',
      fat: '0.167',
      cho: '0.133',
      prt: '0.010',
      cal: 0,
      id: 'us6SgofySCk0QUmBqbLG',
    },
    {
      type: 'Flours',
      prt: '0.214',
      name: 'Almond',
      cal: 0,
      fat: '0.500',
      cho: '0.214',
      id: 'uuFV9rQYn9YpjjMSnSSs',
    },
    {
      type: 'Fruits',
      cho: '0.097',
      name: 'Peaches',
      cal: 0,
      fat: '0.002',
      prt: '0.009',
      id: 'vMrb9LK0OPqILZxyaJ0O',
    },
    {
      prt: '0.182',
      name: 'Catfish',
      cal: 0,
      cho: 0,
      type: 'Seafood',
      fat: '0.070',
      id: 'vdZCaO8pPv1WVyMOS2lA',
    },
    {
      name: 'Tabasco',
      cho: '0.014',
      prt: '0.007',
      cal: 0,
      fat: '0.007',
      type: 'Condiments',
      id: 'vsP8PaVKmVHXFGOUXs4h',
    },
    {
      cho: '0.231',
      fat: '0.538',
      prt: '0.231',
      name: 'Almonds',
      type: 'Nuts/Legumes',
      cal: 0,
      id: 'vy8bVDW5TdDUQ3AYRfUp',
    },
    {
      fat: '0.032',
      cho: '0.484',
      prt: '0.087',
      cal: 0,
      name: 'Ciabatta',
      type: 'Bread',
      id: 'w7fFui5upwSjQVzt7VQA',
    },
    {
      type: 'Seafood',
      cho: '0.020',
      cal: 0,
      name: 'Shrimp',
      fat: '0.020',
      prt: '0.220',
      id: 'wDxVD1HCrJLaOba9y8QQ',
    },
    {
      cal: 0,
      fat: '0.002',
      name: 'Bok Choy',
      type: 'Vegetables',
      cho: '0.018',
      prt: '0.016',
      id: 'wIBiA5GFRj3IOB1ECGJZ',
    },
    {
      type: 'Condiments',
      cho: '0.067',
      fat: '0.001',
      prt: '0.015',
      cal: 0,
      name: 'Salsa',
      id: 'wLs2HmB1pJyiOYS9HIUB',
    },
    {
      prt: '0.019',
      cho: '0.045',
      cal: 0,
      fat: '0.002',
      name: 'Okra',
      type: 'Vegetables',
      id: 'wj4K62sKcjnWlTgzFl0X',
    },
    {
      name: 'Lettuce',
      cal: 0,
      type: 'Vegetables',
      prt: '0.013',
      fat: '0.003',
      cho: '0.033',
      id: 'wqY7XKaf8mPVDKIq6PsA',
    },
    {
      name: 'Soybean',
      fat: '0.087',
      cal: 0,
      type: 'Vegetables',
      prt: '0.180',
      cho: '0.081',
      id: 'xWvfx4xNcB2l1ohtBBx4',
    },
    {
      cho: '0.272',
      cal: 0,
      prt: '0.015',
      fat: '0.001',
      type: 'Vegetables',
      name: 'Yam',
      id: 'xz6lG0ZCdZqavI6hJYWh',
    },
    {
      cho: '0.106',
      fat: '0.001',
      type: 'Fruits',
      prt: '0.008',
      name: 'Grapefruit',
      cal: 0,
      id: 'y7JEa7EyH8qpLxnj5GgA',
    },
    {
      name: 'Wasabi',
      cho: '0.460',
      prt: '0.025',
      type: 'Condiments',
      fat: '0.110',
      cal: 0,
      id: 'y99vGtzP4MXZ5KWBi9Vh',
    },
    {
      type: 'Bread',
      name: 'Bagel',
      cho: '0.524',
      fat: '0.013',
      prt: '0.105',
      cal: 0,
      id: 'yG3pLVQ2T7LiQICfuOlw',
    },
    {
      type: 'Condiments',
      name: 'Hoisin sauce',
      cal: 0,
      prt: '0.031',
      cho: '0.444',
      fat: '0.031',
      id: 'ylMz4yxE3PlLsCZXuVwc',
    },
    {
      type: 'Bread',
      cal: 0,
      name: 'Portuguese Sweet Bread',
      cho: '0.494',
      prt: '0.069',
      fat: '0.007',
      id: 'z9aVBClq1TFV8pqHWmOB',
    },
    {
      type: 'Condiments',
      prt: '0.119',
      fat: '0.552',
      name: 'Pesto',
      cho: '0.081',
      cal: 0,
      id: 'zQiwNuCTGhBQetlx0iGs',
    },
  ],
};
