module.exports.strings = {
  welcome: {
    message: 'Welcome to Bitrupt',
  },

  splash: {
    message: 'Splash Screen',
  },

  signup: {
    email: 'Email',
    enterEmail: 'Enter Email',
    pasword: 'Password',
    enterPassword: 'Enter Password',
    login: 'Login',
    newAcc: 'Create a New Account',
    or: 'Or',
    loginWith: 'Login in with',
    forgotPassword: 'Forgot Password',
  },
  signin: {
    confirmEmail: 'Confirm Email',
    confirmPassword: 'Confirm Password',
    createAcc: 'Create Account',
  },

  completeProfile: {
    labels: {
      name: 'What should we call you?',
      dataSelection:
        'Would you like to participate in our study by sharing some of your in-app data?',
      welcome: 'Welcome, Your profile is complete',
      tutorial: 'If you need a tutorial',
      weight: 'What is your weight? (lbs)',
      height: 'What is your height?',
      gender: 'What is your Gender?',
      DOB: 'What is your Date of birth?',
    },
    placeholders: {
      weight: 'Weight (lbs)',
      name: 'Enter Name',
      dob: 'MM/DD/YYYY',
      height: 'Height',
    },
    buttons: {
      click: 'Click Here',
      next: 'Next',
    },
    screen: {
      Name: 'Name',
      DOB: 'DateOfBirth',
      Gender: 'Gender',
      Height: 'Height',
      Welcome: 'Welcome',
      Weight: 'Weight',
      DataSelection: 'DataSelection',
    },
    radioButtons: {
      yes: 'YES',
      no: 'NO',
      M: 'M',
      F: 'F',
    },
    dataSelectionNote:
      'If you change your mind or want more information, you can adjust your decision in settings.',
    dropdown: {
      feetlist: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      incheslist: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    },
    height: {
      feet: 'ft',
      inch: 'in',
    },
  },
  frequencyList: ['Daily', 'Weekly', 'Biweekly', 'Monthly', 'Never'],
  dayList: [
    'Mondays',
    'Tuesdays',
    'Wednesdays',
    'Thursdays',
    'Fridays',
    'Saturdays',
    'Sundays',
    '*Entire Calendar*',
  ],
  calendar: {
    defaultColor: '#004672',
    theme: 'Theme',
    create: 'create',
    manage: 'manage',
    addRemove: 'add/remove',
    someday: 'Someday',
    pickday: 'Pick a day',
    todo: 'Todo',
  },
  addRemoveTheme: {
    title: 'Add/Remove Theme',
    selectDay: 'Select Day',
    date: '2/27/2021',
    currentTheme: 'Current Theme',
    frequency: 'Frequency',
  },
  calendarMenu: {
    title: 'Calendar Menu',
    select: 'Select',
    themes: 'THEMES',
    todo: 'TO DO',
    calendar: 'Calendar',
  },
  clearTheme: {
    title: 'Clear Theme',
    selectRange: 'Select Range',
  },
  colorPicker: {
    title: 'Colors',
    hex: 'Hex',
  },
  createTheme: {
    title: 'Create Theme',
    newTheme: 'New Theme Name',
    themeColor: 'Theme Color',
  },
  deleteDialog: {
    title: 'Confirm Deletion',
    content: 'Are you sure you want to remove item?',
  },
  editTask: {
    title: 'To Do',
    task: 'Task',
    note: 'Note:',
    noteText: 'This is a note.',
    noTasks: 'No Tasks Yet',
  },
  editTodo: {
    title: 'Edit To Do',
    enterTask: 'Enter Task',
    selectTime: 'Select Time',
    someday: 'SOMEDAY',
    pickDay: 'PICK A DAY',
    notes: 'Notes',
  },
  manageTheme: {
    title: 'Edit Theme',
    selectTheme: 'Select Theme',
    done: 'Done',
    work: 'Work',
    writing: 'Writing',
    party: 'Party',
    rest: 'Rest',
    remove: 'Remove',
  },
  myThemes: {
    title: 'My Themes',
    create: 'CREATE NEW THEME',
    manage: 'MANAGE THEMES',
    addRemove: 'ADD/REMOVE THEMES TO CALENDAR',
    clear: 'CLEAR THEMES FROM CALENDAR',
  },
  todo: {
    today: 'Today',
    someday: 'Someday',
  },
  writingText: {
    today: 'Today is a',
    day: 'day',
  },
  createEvent: {
    title: 'Create Event',
    traitColor: 'Trait Color',
    eventTime: 'Event Time',
    starts: 'STARTS:',
    ends: 'ENDS:',
    startTime: '1:30 PM',
    endTime: '1:45 PM',
  },
  button: {
    clear: 'Clear',
    repeatEvery: 'Repeat Every',
    save: 'Save',
    next: 'Next',
    cancel: 'Cancel',
    delete: 'Delete',
    create: 'Create',
    ok: 'Ok',
    confirm: 'Confirm',
    edit: 'Edit',
  },
  dashboard: {
    details: {
      greetings: 'Greetings,',
      name: 'John Doe',
      today: 'Today is a',
      empty: 'Empty',
      day: 'day.',
      get: 'Get after it!!',
    },
    dayData: {
      labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Dec'],
      data: ['5', '1', '4', '7', '8', '10', '12'],
      legend: ['Weight (lbs)'],
    },
  },
  quarterlyEntry: {
    content1:
      'Which parts of My day require MY total presence? How Might They be impacted THIS QUARTER? how will I adjust?',
    content2:
      'Are there any personal projects or hobbies I would like to work on or continue this quarter?',
    content3:
      'What actions or tasks (subtasks) can I take in my personal projects?',
    content4: 'Any subjects I want to learn more about this quarter?',
    content5: 'What actions or tasks can I take to continue my Education?',
    content6: 'Do I need to clear anything up with Anyone?',
    content7: 'Is there anything I need to let go of?',
    content8:
      'Am I meeting my Dietary expectations? Do I need to make Any adjustments to my calorie intake? do I need to Make any Adjustments to my Macros?',
    content9:
      'Has my routine, and especially my morning routine, improved my overall outlook on my Well-being? If not, what could I change?',
  },
  dailyEntry: {
    content1: 'How am I feeling about this day ahead?',
    content2: 'What is the most important task I need to do?',
    content3: 'What traits do I need to invoke Today?',
    content4: 'Any additional thoughts?',
  },
  weeklyEntry: {
    content1: 'How effective have I been communicating with people around me?',
    content2: 'could I improve my Communication? How?',
    content3:
      'Is there anyone I should reach out to? What should be the focus of conversation?',
    content4: 'How focused was I this week?',
    content5: 'What actions could I do to improve my focus?',
    content6: 'Any new or lingering situations to address?',
  },
  itinerary: {
    time: [
      '12:00',
      '1:00',
      '2:00',
      '3:00',
      '4:00',
      '5:00',
      '6:00',
      '7:00',
      '8:00',
      '9:00',
      '10:00',
      '11:00',
    ],
    sleep: 'Sleep',
    work: 'Work',
    nightRoutine: 'Night Routine',
    morningRoutine: 'Morning Routine',
    social: 'Email / Social',
    meal1: 'Meal #1',
    meal2: 'Meal #2',
    meal3: 'Meal #3',
    exercise: 'Exercise',
    open: 'Open',
    lecture: 'Lecture',
  },

  nutrition: {
    meals: {
      totalItems: [
        {
          id: 0,
        },
        {
          id: 1,
          item: 'ITEM 1',
          fat: 20,
          prt: 20,
          cho: 0,
          cal: 300,
        },
        {
          id: 2,
          item: 'ITEM 2',
          fat: 10,
          prt: 15,
          cho: 0,
          cal: 150,
        },
        {
          id: 3,
          item: 'ITEM 3',
          fat: 30,
          prt: 10,
          cho: 0,
          cal: 310,
        },
        {
          id: 4,
          item: 'ITEM 4',
          fat: 0,
          prt: 0,
          cho: 30,
          cal: 120,
        },
      ],
      checked: 'From Directory',
      mealTable: {
        fat: 'FAT',
        prt: 'PRT',
        cho: 'CHO',
        cal: 'CAL',
        total: 'Total',
      },
      editMeal: {
        edit: 'Edit Item',
        input: {
          itemTitle: 'Item Name',
          itemText: 'Enter Name',
          fatTitle: 'Enter Fat (Grams)',
          fatText: 'Amount Fat (g)',
          proteinTitle: 'Enter Protein (Grams)',
          proteinText: 'Amount Protein (g)',
          carbsTitle: 'Enter Carbs (Grams)',
          carbsText: 'Amount Carbs (g)',
        },
        save: 'Save',
        delete: 'Delete',
      },
      deleteMeal: {
        confirmTitle: 'Confirm Deletion',
        confirmBody: 'Are you sure you want to remove them?',
        cancel: 'Cancel',
        ok: 'Ok',
      },
      addMeal: {
        add: 'Add Meal Item',
        select: 'Select',
        radio1: 'From Directory',
        radio2: 'Custom Item',
        next: 'Next',
      },
      addCustomMeal: {
        addItem: 'Add Item',
        add: 'Add',
      },
    },
  },
  MyProfile: {
    badge: {
      overweight: 'Overweight',
      normalweight: 'Normal weight',
      underweight: 'Underweight',
      obesity1: 'Obesity class I',
      obesity2: 'Obesity class II',
      obesity3: 'Obesity class III',
    },
  },
};
