module.exports.wheelPickerItems = {
  days: [
    {id: 1, value: '1'},
    {id: 2, value: '2'},
    {id: 3, value: '3'},
    {id: 4, value: '4'},
    {id: 5, value: '5'},
    {id: 6, value: '6'},
    {id: 7, value: '7'},
    {id: 8, value: '8'},
    {id: 9, value: '9'},
    {id: 10, value: '10'},
    {id: 11, value: '11'},
    {id: 12, value: '12'},
    {id: 13, value: '13'},
    {id: 14, value: '14'},
    {id: 15, value: '15'},
    {id: 16, value: '16'},
    {id: 17, value: '17'},
    {id: 18, value: '18'},
    {id: 19, value: '19'},
    {id: 20, value: '20'},
    {id: 21, value: '21'},
    {id: 22, value: '22'},
    {id: 23, value: '23'},
    {id: 24, value: '24'},
    {id: 25, value: '25'},
    {id: 26, value: '26'},
    {id: 27, value: '27'},
    {id: 28, value: '28'},
    {id: 29, value: '29'},
    {id: 30, value: '30'},
    {id: 31, value: '31'},
  ],
  months: [
    {id: 1, value: 'Jan'},
    {id: 2, value: 'Feb'},
    {id: 3, value: 'Mar'},
    {id: 4, value: 'Apr'},
    {id: 5, value: 'May'},
    {id: 6, value: 'Jun'},
    {id: 7, value: 'Jul'},
    {id: 8, value: 'Aug'},
    {id: 9, value: 'Sep'},
    {id: 10, value: 'Oct'},
    {id: 11, value: 'Nov'},
    {id: 12, value: 'Dec'},
  ],
  years: [
    {id: 1, value: '2021'},
    {id: 2, value: '2022'},
    {id: 3, value: '2023'},
    {id: 4, value: '2024'},
    {id: 5, value: '2025'},
    {id: 6, value: '2026'},
    {id: 7, value: '2027'},
    {id: 8, value: '2028'},
    {id: 9, value: '2029'},
    {id: 10, value: '2030'},
  ],
  workoutDays: [
    {id: 1, value: '1'},
    {id: 2, value: '2'},
    {id: 3, value: '3'},
    {id: 4, value: '4'},
    {id: 5, value: '5'},
    {id: 6, value: '6'},
    {id: 7, value: '7'},
  ],
  weeks: [
    {id: 1, value: '1'},
    {id: 2, value: '2'},
    {id: 3, value: '3'},
    {id: 4, value: '4'},
    {id: 5, value: '5'},
    {id: 6, value: '6'},
    {id: 7, value: '7'},
    {id: 8, value: '8'},
    {id: 9, value: '9'},
    {id: 10, value: '10'},
    {id: 11, value: '11'},
    {id: 12, value: '12'},
    {id: 13, value: '13'},
    {id: 14, value: '14'},
    {id: 15, value: '15'},
    {id: 16, value: '16'},
    {id: 17, value: '17'},
    {id: 18, value: '18'},
    {id: 19, value: '19'},
    {id: 20, value: '20'},
    {id: 21, value: '21'},
    {id: 22, value: '22'},
    {id: 23, value: '23'},
    {id: 24, value: '24'},
    {id: 25, value: '25'},
    {id: 26, value: '26'},
    {id: 27, value: '27'},
    {id: 28, value: '28'},
    {id: 29, value: '29'},
    {id: 30, value: '30'},
  ],
  units: [
    {id: 1, value: 'tbsp'},
    {id: 2, value: 'mcg'},
    {id: 3, value: 'mg'},
    {id: 4, value: 'g'},
    {id: 5, value: 'kg'},
    {id: 6, value: 'lbs'},
    {id: 7, value: 'oz'},
  ],
  mealUnits: [
    {id: 1, value: 'g'},
    {id: 2, value: 'kg'},
    {id: 3, value: 'lbs'},
    {id: 4, value: 'oz'},
  ],
  exercises: [
    {id: 1, value: 'Bridges', met: 6},
    {id: 2, value: 'Mountain Climbers', met: 4},
    {id: 3, value: 'Sit-ups', met: 3.3},
    {id: 4, value: 'Push ups', met: 3.3},
    {id: 5, value: 'Walking Burpees', met: 3.5},
    {id: 6, value: 'Squats', met: 3.5},
    {id: 7, value: 'Lunges', met: 4.1},
    {id: 8, value: 'Jumping Jacks', met: 7.7},
  ],
  sets: [
    {id: 1, value: '1'},
    {id: 2, value: '2'},
    {id: 3, value: '3'},
    {id: 4, value: '4'},
    {id: 5, value: '5'},
    {id: 6, value: '6'},
    {id: 7, value: '7'},
    {id: 8, value: '8'},
    {id: 9, value: '9'},
    {id: 10, value: '10'},
  ],
  exerciseUnits: [
    {id: 1, value: 'Yards', unit: 'yd'},
    {id: 2, value: 'Meters', unit: 'm'},
    {id: 3, value: 'Kilometers', unit: 'km'},
    {id: 4, value: 'Miles', unit: 'mi'},
    {id: 5, value: 'Reps', unit: 'Rp'},
    {id: 6, value: 'Seconds', unit: 'Sc'},
    {id: 7, value: 'Minutes', unit: 'Mn'},
    {id: 8, value: 'Hours', unit: 'Hr'},
  ],
  feets: [
    {id: 1, value: '1'},
    {id: 2, value: '2'},
    {id: 3, value: '3'},
    {id: 4, value: '4'},
    {id: 5, value: '5'},
    {id: 6, value: '6'},
    {id: 7, value: '7'},
    {id: 8, value: '8'},
    {id: 9, value: '9'},
  ],
  inches: [
    {id: 0, value: '0'},
    {id: 1, value: '1'},
    {id: 2, value: '2'},
    {id: 3, value: '3'},
    {id: 4, value: '4'},
    {id: 5, value: '5'},
    {id: 6, value: '6'},
    {id: 7, value: '7'},
    {id: 8, value: '8'},
    {id: 9, value: '9'},
    {id: 10, value: '10'},
    {id: 11, value: '11'},
  ],
  hours: [
    {id: 1, value: '1'},
    {id: 2, value: '2'},
    {id: 3, value: '3'},
    {id: 4, value: '4'},
    {id: 5, value: '5'},
    {id: 6, value: '6'},
    {id: 7, value: '7'},
    {id: 8, value: '8'},
    {id: 9, value: '9'},
    {id: 10, value: '10'},
    {id: 11, value: '11'},
    {id: 12, value: '12'},
  ],
  hoursFormat24: [
    {id: 1, value: '1'},
    {id: 2, value: '2'},
    {id: 3, value: '3'},
    {id: 4, value: '4'},
    {id: 5, value: '5'},
    {id: 6, value: '6'},
    {id: 7, value: '7'},
    {id: 8, value: '8'},
    {id: 9, value: '9'},
    {id: 10, value: '10'},
    {id: 11, value: '11'},
    {id: 12, value: '12'},
    {id: 13, value: '13'},
    {id: 14, value: '14'},
    {id: 15, value: '15'},
    {id: 16, value: '16'},
    {id: 17, value: '17'},
    {id: 18, value: '18'},
    {id: 19, value: '19'},
    {id: 20, value: '20'},
    {id: 21, value: '21'},
    {id: 22, value: '22'},
    {id: 23, value: '23'},
  ],
  minutes: [
    {id: 0, value: '00'},
    {id: 1, value: '01'},
    {id: 2, value: '02'},
    {id: 3, value: '03'},
    {id: 4, value: '04'},
    {id: 5, value: '05'},
    {id: 6, value: '06'},
    {id: 7, value: '07'},
    {id: 8, value: '08'},
    {id: 9, value: '09'},
    {id: 10, value: '10'},
    {id: 11, value: '11'},
    {id: 12, value: '12'},
    {id: 13, value: '13'},
    {id: 14, value: '14'},
    {id: 15, value: '15'},
    {id: 16, value: '16'},
    {id: 17, value: '17'},
    {id: 18, value: '18'},
    {id: 19, value: '19'},
    {id: 20, value: '20'},
    {id: 21, value: '21'},
    {id: 22, value: '22'},
    {id: 23, value: '23'},
    {id: 24, value: '24'},
    {id: 25, value: '25'},
    {id: 26, value: '26'},
    {id: 27, value: '27'},
    {id: 28, value: '28'},
    {id: 29, value: '29'},
    {id: 30, value: '30'},
    {id: 31, value: '31'},
    {id: 32, value: '32'},
    {id: 33, value: '33'},
    {id: 34, value: '34'},
    {id: 35, value: '35'},
    {id: 36, value: '36'},
    {id: 37, value: '37'},
    {id: 38, value: '38'},
    {id: 39, value: '39'},
    {id: 40, value: '40'},
    {id: 41, value: '41'},
    {id: 42, value: '42'},
    {id: 43, value: '43'},
    {id: 44, value: '44'},
    {id: 45, value: '45'},
    {id: 46, value: '46'},
    {id: 47, value: '47'},
    {id: 48, value: '48'},
    {id: 49, value: '49'},
    {id: 50, value: '50'},
    {id: 51, value: '51'},
    {id: 52, value: '52'},
    {id: 53, value: '53'},
    {id: 54, value: '54'},
    {id: 55, value: '55'},
    {id: 56, value: '56'},
    {id: 57, value: '57'},
    {id: 58, value: '58'},
    {id: 59, value: '59'},
  ],
  timeFormat: [
    {id: 0, value: 'AM'},
    {id: 1, value: 'PM'},
  ],
  minutesWithDiff15: [
    {id: 0, value: '00'},
    {id: 1, value: '15'},
    {id: 2, value: '30'},
    {id: 3, value: '45'},
  ],
  frequency: [
    {id: 1, value: 'Daily'},
    {id: 2, value: 'Weekly'},
    {id: 3, value: 'BiWeekly'},
    {id: 4, value: 'Monthly'},
    {id: 5, value: 'Never'},
  ],
  calendarDays: [
    {id: 1, value: 'Mondays'},
    {id: 2, value: 'Tuesdays'},
    {id: 3, value: 'Wednesdays'},
    {id: 4, value: 'Thursdays'},
    {id: 5, value: 'Fridays'},
    {id: 6, value: 'Saturdays'},
    {id: 7, value: 'Sundays'},
    {id: 8, value: 'Entire Calendar'},
  ],
};
