import {StyleSheet} from 'react-native';
import {RFValue} from 'react-native-responsive-fontsize';
import {colors} from '../../../resources';

export default StyleSheet.create({
  calendarTitle: {
    color: colors.white,
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    paddingTop: 20,
  },
  writingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: 20,
    marginBottom: 0,
  },
  writingButton: {
    padding: 10,
    paddingHorizontal: 15,
    fontSize: 18,
    color: colors.white,
  },
  writingButtonContainer: {
    borderRadius: 30,
    marginHorizontal: 10,
  },
  taskToday: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.secondary,
    marginBottom: 10,
    width: 100,
    backgroundColor: colors.background,
  },
  todoSubheading: {
    fontSize: 26,
    color: colors.white,
    fontWeight: 'bold',
    marginVertical: 20,
  },
  taskSomeday: {
    borderRadius: 20,
    backgroundColor: colors.secondary,
    width: 100,
    marginBottom: 10,
  },
  modalContainer: {
    backgroundColor: colors.nonEditableOverlays,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.secondary,
    padding: 20,
    margin: 2,
  },
  editModalContainer: {
    margin: 2,
    borderWidth: 1,
    borderRadius: 20,
    paddingVertical: 30,
    paddingHorizontal: 20,
    borderColor: colors.secondary,
    backgroundColor: colors.background,
  },
  title: {
    color: colors.white,
    fontSize: 24,
  },
  headline: {color: colors.mainFont, fontSize: 30, fontWeight: 'bold'},
  editTitle: {
    color: colors.secondary,
    fontSize: 24,
    marginBottom: 8,
  },
  submitButton: {
    borderRadius: 20,
    backgroundColor: colors.secondary,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
  },
  submitButtonLabel: {
    color: colors.black,
    fontWeight: 'bold',
    fontSize: 20,
  },
  modalTaskText: {
    paddingTop: 6,
    paddingLeft: 10,
    fontSize: 18,
    color: colors.white,
  },
  modalText: {
    paddingTop: 6,
    paddingLeft: 10,
    fontSize: 16,
    color: colors.white,
  },
  input: {
    width: '100%',
    height: RFValue(45),
    borderRadius: RFValue(25),
    fontSize: RFValue(15),
    color: colors.mainFont,
    paddingHorizontal: RFValue(15),
    backgroundColor: colors.nonEditableOverlays,
  },
  notesInput: {
    height: RFValue(150),
    fontSize: RFValue(15),
    marginTop: RFValue(15),
    color: colors.mainFont,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderRadius: 15,
    borderColor: colors.secondary,
    paddingVertical: RFValue(10),
    paddingHorizontal: RFValue(20),
    backgroundColor: colors.nonEditableOverlays,
  },
  modalHead: {flexDirection: 'row', justifyContent: 'space-between'},
  date: {
    color: colors.tertiary,
    fontSize: 18,
    marginBottom: 10,
  },
  repeatEvery: {
    backgroundColor: colors.nonEditableOverlays,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.secondary,
    width: 200,
  },
  select: {
    backgroundColor: colors.nonEditableOverlays,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.secondary,
  },
  colorBackground: {
    flexDirection: 'row',
    marginLeft: 10,
    backgroundColor: colors.overlays,
    padding: 5,
  },
  dialogContainer: {
    backgroundColor: colors.nonEditableOverlays,
    borderWidth: 1,
    borderColor: colors.qccentError,
    alignItems: 'center',
  },
  confirmButton: {
    borderWidth: 1,
    borderBottomColor: colors.white,
    borderTopColor: colors.white,
    margin: 0,
  },
  selectTimeOptionsView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 30,
  },
  dateText: {
    fontWeight: 'bold',
    fontSize: RFValue(14),
    color: colors.tertiary,
  },
  bottomTextView: {
    alignSelf: 'center',
    marginVertical: RFValue(30),
  },
  loaderView: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10,
    opacity: 0.6,
    borderRadius: 10,
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  headingView: {
    marginTop: RFValue(10),
    alignItems: 'center',
  },
  headingText: {
    fontSize: RFValue(60),
    fontWeight: 'bold',
    color: colors.white,
  },
  bottomTextView2: {
    marginTop: 30,
    alignSelf: 'center',
  },
  emptyDayView: {
    borderWidth: 2,
    borderRadius: 30,
    borderStyle: 'dashed',
    paddingVertical: 5,
    marginHorizontal: 5,
    paddingHorizontal: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: colors.secondary,
  },
  emptyDayText: {
    fontSize: RFValue(18),
    fontWeight: 'bold',
    color: colors.white,
  },
});
