export const SET_USER = 'SET_USER';

export const SET_JOURNAL_ENTRY = 'SET_JOURNAL_ENTRY';
export const EDIT_JOURNAL_ENTRY = 'EDIT_JOURNAL_ENTRY';
export const GET_JOURNAL_ENTRIES = 'GET_JOURNAL_ENTRIES';
export const GET_ALL_JOURNAL_ENTRIES = 'GET_ALL_JOURNAL_ENTRIES';

export const GET_MEALS = 'GET_MEALS';
export const ADD_MEAL = 'ADD_MEAL';
export const DELETE_MEAL = 'DELETE_MEAL';
export const SET_MEAL_ITEMS = 'SET_MEAL_ITEMS';
export const GET_MEAL_ITEMS = 'GET_MEAL_ITEMS';
export const ADD_MEAL_ITEMS = 'ADD_MEAL_ITEMS';
export const EDIT_MEAL_ITEMS = 'EDIT_MEAL_ITEMS';
export const DELETE_MEAL_ITEMS = 'DELETE_MEAL_ITEMS';

export const GET_SUPPLEMENTS = 'GET_SUPPLEMENTS';
export const ADD_SUPPLEMENT = 'ADD_SUPPLEMENT';
export const DELETE_SUPPLEMENT = 'DELETE_SUPPLEMENT';
export const SET_SUPPLEMENT_ITEMS = 'SET_SUPPLEMENT_ITEMS';
export const GET_SUPPLEMENT_ITEMS = 'GET_SUPPLEMENT_ITEMS';
export const ADD_SUPPLEMENT_ITEMS = 'ADD_SUPPLEMENT_ITEMS';
export const EDIT_SUPPLEMENT_ITEMS = 'EDIT_SUPPLEMENT_ITEMS';
export const DELETE_SUPPLEMENT_ITEMS = 'DELETE_SUPPLEMENT_ITEMS';

export const GET_ROUTINES = 'GET_ROUTINES';
export const ADD_ROUTINE = 'ADD_ROUTINE';
export const DELETE_ROUTINE = 'DELETE_ROUTINE';

export const GET_BRUNCH_BODY_PLANS = 'GET_BRUNCH_BODY_PLANS';

export const GET_WORKOUTS = 'GET_WORKOUTS';
export const ADD_WORKOUT = 'ADD_WORKOUT';
export const EDIT_WORKOUT = 'EDIT_WORKOUT';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';

export const GET_ROUTINE_ITEMS = 'GET_ROUTINE_ITEMS';
export const ADD_ROUTINE_ITEMS = 'ADD_ROUTINE_ITEMS';
export const EDIT_ROUTINE_ITEMS = 'EDIT_ROUTINE_ITEMS';
export const DELETE_ROUTINE_ITEMS = 'DELETE_ROUTINE_ITEMS';

export const GET_CUSTOM_PLANS = 'GET_CUSTOM_PLANS';
export const ADD_CUSTOM_PLANS = 'ADD_CUSTOM_PLANS';
export const DELETE_CUSTOM_PLANS = 'DELETE_CUSTOM_PLANS';

export const GET_WEEK_PLAN = 'GET_WEEK_PLAN';
export const GET_BRUNCH_BODY_WEEK_PLAN = 'GET_BRUNCH_BODY_WEEK_PLAN';
export const ADD_WEEK_PLAN = 'ADD_WEEK_PLAN';
export const EDIT_WEEK_PLAN = 'EDIT_WEEK_PLAN';

export const GET_EXERCISES = 'GET_EXERCISES';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';

export const GET_TODO_TASKS = 'GET_TODO_TASKS';
export const ADD_TODO_TASK = 'ADD_TODO_TASK';
export const EDIT_TODO_TASK = 'EDIT_TODO_TASK';
export const DELETE_TODO_TASK = 'DELETE_TODO_TASK';

export const ADD_THEME = 'ADD_THEME';
export const GET_THEMES = 'GET_THEMES';
export const EDIT_THEME = 'EDIT_THEME';
export const SET_THEME = 'SET_THEME';
export const DELETE_THEME = 'DELETE_THEME';

export const SET_REPEATED_THEME = 'SET_REPEATED_THEME';
export const ADD_REPEATED_THEME = 'ADD_REPEATED_THEME';
export const EDIT_REPEATED_THEME = 'EDIT_REPEATED_THEME';
export const CLEAR_THEME_DAYS = 'CLEAR_THEME_DAYS';
export const CLEAR_CURRENT_THEME = 'CLEAR_CURRENT_THEME';
export const SET_THEME_WITH_FREQUENCY = 'SET_THEME_WITH_FREQUENCY';

export const GET_TRAITS = 'GET_TRAITS';

export const GET_MEAL_CATEGORIES = 'GET_MEAL_CATEGORIES';
export const GET_MEALS_DIRECTORY = 'GET_MEALS_DIRECTORY';

export const GET_EXERCISE_DIRECTORY = 'GET_EXERCISE_DIRECTORY';

export const MERGE_EXERCISES = 'MERGE_EXERCISES';

export const ADD_COMPLETED_WORKOUT = 'ADD_COMPLETED_WORKOUT';
